# Web Data Science
## Week 05 - Static web pages

INFO 4871/5871 - Fall 2024  
[Brian C. Keegan, Ph.D.](http://brianckeegan.com/)  
[Assistant Professor, Department of Information Science](https://www.colorado.edu/cmci/people/information-science/brian-c-keegan)  
University of Colorado Boulder  

Copyright and distributed under an [MIT License](https://opensource.org/licenses/MIT)

## Parsing HTML data into tabular data

The overall goal we have as researchers in scraping data from the web is converting data from one structured format (HTML's tree-like structures) into another structured format (probably a tabular structure with rows and columns). 
This could involve simply reading tables out of a webpage all the way up to taking irregularly-structured HTML elements into a tabular format. 

We are going to make some use of the [`pandas`](https://pandas.pydata.org/) library ("**pan**el **da**ta", not the cute animal), which is Python's implementation of a data frame concept. This is a very powerful and complex library that I typically spend more than 12 hours of lecture teaching in intermediate programming classes. I hope to convey some important elements as we work through material, but it is far beyond the scope of this class to be able to cover all the fundamentals and syntax. 

Let's begin by importing the libraries we'll need in this notebook: requests, BeautifulSoup, and pandas

In [3]:
# Most straight-forward way to import a library in Python
import requests

# BeautifulSoup is a module inside the "bs4" library, we only import the BeautifulSoup module
from bs4 import BeautifulSoup

# We import pandas but give the library a shortcut alias "pd" since we will call its functions so much
import pandas as pd

# Define a user-agent string you'll use throughout the notebook for all your requests
user_agent = {'user-agent':'info-5871/0.0 Web Data Science, brian.keegan@colorado.edu'}

### Reading an HTML table into Python

[The Numbers](http://www.the-numbers.com) is a popular source of data about movies' box office revenue numbers. Their daily domestic charts are HTML tables with the top-grossing movies for each day of the year, going back for several years. This [table](https://www.the-numbers.com/box-office-chart/daily/2018/12/25) for Christmas day in 2018 has coluns for the current week's ranking, previous week's ranking, name of movie, distributor, gross, change over the previous week, number of theaters, revenue per theater, total gross, and number of days since release. This looks like a fairly straightforward table that could be read directly into data frame-like structure.

Using the Inspect tool, we can see the table exists as a `<table border="0" ... align="CENTER">` element with child tags like `<tbody>` and `<tr>` (table row). Each `<tr>` has `<td>` which defines each of the cells and their content. For more on how HTML defines tables, check out [this tutoral](https://www.w3schools.com/html/html_tables.asp).

Using `requests` and `BeautifulSoup` we would get this webpage's HTML, turn it into soup, and then find the table (`<table>`) or the table rows (`<tr>`) and pull out their content.

In [4]:
# Make the request
xmas_bo_raw = requests.get(
    'https://www.the-numbers.com/box-office-chart/daily/2024/9/24',
    headers = user_agent).text

# Turn into soup, specify the HTML parser
xmas_bo_soup = BeautifulSoup(xmas_bo_raw,'html.parser')

# Use .find_all to retrieve all the tables in the page
xmas_bo_tables = xmas_bo_soup.find_all('table')

xmas_bo_tables

[<table class="pintable">
 <tr>
 <td class="previous"><a href="/box-office-chart/daily/2024/09/03">← Previous Chart</a></td>
 <td class="index"><a href="/box-office">Chart Index</a></td>
 <td class="next"><a href="/box-office-chart/daily/2024/09/05">Next Chart →</a></td>
 </tr>
 </table>,
 <table class="table-responsive display compact dataTable" id="box_office_daily_table" style="border:none; width:100%">
 <thead><tr><th> </th><th> </th><th>Movie Title</th><th>Distributor</th><th>Gross</th><th>%YD</th><th>%LW</th><th>Theaters</th><th>Per<br/>Theater</th><th>Total<br/>Gross</th><th>Days In<br/>Release</th></tr></thead><tbody>
 <tr>
 <td class="data" data-sort="1">1</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Beetlejuice-Beetlejuice-(2024)#tab=box-office">Beetlejuice Beetlejuice</a></b></td>
 <td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>
 <td class="data">$2,466,902</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="4172">4,172</td>
 <td class="data chart_grey" data-sort="591">$591</td>
 <td class="data" data-sort="230938348">$230,938,348</td>
 <td class="data">19</td>
 </tr>
 <tr>
 <td class="data" data-sort="2">2</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Transformers-One-(2024)#tab=box-office">Transformers One</a></b></td>
 <td><a href="/market/distributor/Paramount-Pictures">Paramount Pi…</a></td>
 <td class="data">$2,003,977</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="3978">3,978</td>
 <td class="data chart_grey" data-sort="504">$504</td>
 <td class="data" data-sort="27871915">$27,871,915</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="3">3</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Speak-No-Evil-(2024)#tab=box-office">Speak No Evil</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$856,980</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="3375">3,375</td>
 <td class="data chart_grey" data-sort="254">$254</td>
 <td class="data" data-sort="22752895">$22,752,895</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data" data-sort="4">4</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Substance-The-(2024)#tab=box-office">The Substance</a></b></td>
 <td><a href="/market/distributor/MUBI">MUBI</a></td>
 <td class="data">$611,797</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1949">1,949</td>
 <td class="data chart_grey" data-sort="314">$314</td>
 <td class="data" data-sort="4239480">$4,239,480</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="5">5</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Never-Let-Go-(2024)#tab=box-office">Never Let Go</a></b></td>
 <td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>
 <td class="data">$585,690</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="2667">2,667</td>
 <td class="data chart_grey" data-sort="220">$220</td>
 <td class="data" data-sort="5409643">$5,409,643</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="6">6</td>
 <td class="data" data-sort="6">(6)</td>
 <td><b><a href="/movie/Deadpool-and-Wolverine-(2024)#tab=box-office">Deadpool &amp; Wolverine</a></b></td>
 <td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>
 <td class="data">$415,308</td>
 <td class="data chart_down" data-sort="-68">-68%</td>
 <td class="data chart_down" data-sort="-74">-74%</td>
 <td class="data" data-sort="2450">2,450</td>
 <td class="data chart_grey" data-sort="170">$170</td>
 <td class="data" data-sort="627950324">$627,950,324</td>
 <td class="data">61</td>
 </tr>
 <tr>
 <td class="data chart_up" data-sort="7"><b>7</b></td>
 <td class="data" data-sort="8">(8)</td>
 <td><b><a href="/movie/Reagan-(2024)#tab=box-office">Reagan</a></b></td>
 <td><a href="/market/distributor/ShowBiz-Direct">ShowBiz Direct</a></td>
 <td class="data">$345,565</td>
 <td class="data chart_down" data-sort="-73">-73%</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1850">1,850</td>
 <td class="data chart_grey" data-sort="187">$187</td>
 <td class="data" data-sort="27076790">$27,076,790</td>
 <td class="data">26</td>
 </tr>
 <tr>
 <td class="data" data-sort="8">8</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Am-I-Racist-(2024)#tab=box-office">Am I Racist?</a></b></td>
 <td><a href="/market/distributor/SDG-Releasing">SDG Releasing</a></td>
 <td class="data">$333,907</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1600">1,600</td>
 <td class="data chart_grey" data-sort="209">$209</td>
 <td class="data" data-sort="9534617">$9,534,617</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data chart_up" data-sort="9"><b>9</b></td>
 <td class="data" data-sort="10">(10)</td>
 <td><b><a href="/movie/Forge-The-(2024)#tab=box-office">The Forge</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$189,784</td>
 <td class="data chart_down" data-sort="-73">-73%</td>
 <td class="data chart_down" data-sort="-71">-71%</td>
 <td class="data" data-sort="1181">1,181</td>
 <td class="data chart_grey" data-sort="161">$161</td>
 <td class="data" data-sort="26637232">$26,637,232</td>
 <td class="data">33</td>
 </tr>
 <tr>
 <td class="data" data-sort="10">10</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Killers-Game-The-(2024)#tab=box-office">The Killer’s Game</a></b></td>
 <td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>
 <td class="data">$188,157</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="2623">2,623</td>
 <td class="data chart_grey" data-sort="72">$72</td>
 <td class="data" data-sort="5124785">$5,124,785</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data chart_down" data-sort="11">11</td>
 <td class="data" data-sort="9">(9)</td>
 <td><b><a href="/movie/Alien-Romulus-(2024)#tab=box-office">Alien: Romulus</a></b></td>
 <td><a href="/market/distributor/20th-Century-Studios">20th Century…</a></td>
 <td class="data">$186,859</td>
 <td class="data chart_down" data-sort="-81">-81%</td>
 <td class="data chart_down" data-sort="-87">-87%</td>
 <td class="data" data-sort="1350">1,350</td>
 <td class="data chart_grey" data-sort="138">$138</td>
 <td class="data" data-sort="103933623">$103,933,623</td>
 <td class="data">40</td>
 </tr>
 <tr>
 <td class="data" data-sort="12">12</td>
 <td class="data" data-sort="12">(12)</td>
 <td><b><a href="/movie/It-Ends-With-Us-(2024)#tab=box-office">It Ends With Us</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$152,684</td>
 <td class="data chart_down" data-sort="-82">-82%</td>
 <td class="data chart_down" data-sort="-88">-88%</td>
 <td class="data" data-sort="1164">1,164</td>
 <td class="data chart_grey" data-sort="131">$131</td>
 <td class="data" data-sort="147104126">$147,104,126</td>
 <td class="data">47</td>
 </tr>
 <tr>
 <td class="data" data-sort="13">13</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Gods-Not-Dead-In-God-We-Trust-(2024)#tab=box-office">God’s Not Dead: In God We…</a></b></td>
 <td><a href="/market/distributor/Fathom-Events">Fathom Events</a></td>
 <td class="data">$89,297</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="444">444</td>
 <td class="data chart_grey" data-sort="201">$201</td>
 <td class="data" data-sort="3196261">$3,196,261</td>
 <td class="data">13</td>
 </tr>
 <tr>
 <td class="data" data-sort="14">14</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Front-Room-The-(2024)#tab=box-office">The Front Room</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$72,722</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="98">98</td>
 <td class="data chart_grey" data-sort="742">$742</td>
 <td class="data" data-sort="3401469">$3,401,469</td>
 <td class="data">19</td>
 </tr>
 <tr>
 <td class="data chart_up" data-sort="15"><b>15</b></td>
 <td class="data" data-sort="17">(17)</td>
 <td><b><a href="/movie/Blink-Twice-(2024)#tab=box-office">Blink Twice</a></b></td>
 <td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>
 <td class="data">$54,000</td>
 <td class="data chart_down" data-sort="-92">-92%</td>
 <td class="data chart_down" data-sort="-93">-93%</td>
 <td class="data" data-sort="305">305</td>
 <td class="data chart_grey" data-sort="177">$177</td>
 <td class="data" data-sort="22859926">$22,859,926</td>
 <td class="data">33</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="18">(18)</td>
 <td><b><a href="/movie/Twisters-(2024)#tab=box-office">Twisters</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$53,155</td>
 <td class="data chart_down" data-sort="-93">-93%</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data" data-sort="650">650</td>
 <td class="data chart_grey" data-sort="82">$82</td>
 <td class="data" data-sort="267276205">$267,276,205</td>
 <td class="data">68</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Despicable-Me-4-(2024)#tab=box-office">Despicable Me 4</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$48,520</td>
 <td class="data chart_down" data-sort="-83">-83%</td>
 <td class="data chart_down" data-sort="-89">-89%</td>
 <td class="data" data-sort="796">796</td>
 <td class="data chart_grey" data-sort="61">$61</td>
 <td class="data" data-sort="360461930">$360,461,930</td>
 <td class="data">84</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/My-Old-Ass-(2024)#tab=box-office">My Old Ass</a></b></td>
 <td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>
 <td class="data">$35,230</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="33">33</td>
 <td class="data chart_grey" data-sort="1068">$1,068</td>
 <td class="data" data-sort="570072">$570,072</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Faith-of-Angels-(2024)#tab=box-office">Faith of Angels</a></b></td>
 <td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>
 <td class="data">$16,129</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="30">30</td>
 <td class="data chart_grey" data-sort="538">$538</td>
 <td class="data" data-sort="174284">$174,284</td>
 <td class="data">13</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Critic-The-(2024)#tab=box-office">The Critic</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$11,818</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="110">110</td>
 <td class="data chart_grey" data-sort="107">$107</td>
 <td class="data" data-sort="379732">$379,732</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Inside-Out-2-(2024)#tab=box-office">Inside Out 2</a></b></td>
 <td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>
 <td class="data">$11,555</td>
 <td class="data chart_down" data-sort="-94">-94%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="250">250</td>
 <td class="data chart_grey" data-sort="46">$46</td>
 <td class="data" data-sort="652894496">$652,894,496</td>
 <td class="data">103</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Dan-Da-Dan-First-Encounter-(2024-Japan)#tab=box-office">DAN DA DAN: First Encounter</a></b></td>
 <td><a href="/market/distributor/GKIDS">GKIDS</a></td>
 <td class="data">$9,838</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="81">81</td>
 <td class="data chart_grey" data-sort="121">$121</td>
 <td class="data" data-sort="1030358">$1,030,358</td>
 <td class="data">12</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Sing-Sing-(2024)#tab=box-office">Sing Sing</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$7,592</td>
 <td class="data" data-sort="0"> </td>
 <td class="data chart_down" data-sort="-80">-80%</td>
 <td class="data" data-sort="35">35</td>
 <td class="data chart_grey" data-sort="217">$217</td>
 <td class="data" data-sort="2733310">$2,733,310</td>
 <td class="data">75</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Trap-(2024)#tab=box-office">Trap</a></b></td>
 <td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>
 <td class="data">$7,466</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="78">78</td>
 <td class="data chart_grey" data-sort="96">$96</td>
 <td class="data" data-sort="42714375">$42,714,375</td>
 <td class="data">54</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Shade-The-(2024)#tab=box-office">The Shade</a></b></td>
 <td><a href="/market/distributor/Level-33">Level 33</a></td>
 <td class="data">$6,595</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="240">240</td>
 <td class="data chart_grey" data-sort="27">$27</td>
 <td class="data" data-sort="54903">$54,903</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Different-Man-A-(2024)#tab=box-office">A Different Man</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$5,942</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="4">4</td>
 <td class="data chart_grey" data-sort="1486">$1,486</td>
 <td class="data" data-sort="60687">$60,687</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Didi-(2024)#tab=box-office">Dìdi (弟弟)</a></b></td>
 <td><a href="/market/distributor/Focus-Features">Focus Features</a></td>
 <td class="data">$5,625</td>
 <td class="data chart_down" data-sort="-85">-85%</td>
 <td class="data chart_down" data-sort="-91">-91%</td>
 <td class="data" data-sort="51">51</td>
 <td class="data chart_grey" data-sort="110">$110</td>
 <td class="data" data-sort="4830440">$4,830,440</td>
 <td class="data">61</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Strange-Darling-(2024)#tab=box-office">Strange Darling</a></b></td>
 <td><a href="/market/distributor/Magenta-Light-Studios">Magenta Ligh…</a></td>
 <td class="data">$3,479</td>
 <td class="data chart_down" data-sort="-96">-96%</td>
 <td class="data chart_down" data-sort="-98">-98%</td>
 <td class="data" data-sort="30">30</td>
 <td class="data chart_grey" data-sort="116">$116</td>
 <td class="data" data-sort="3072283">$3,072,283</td>
 <td class="data">33</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/My-Penguin-Friend-(2024)#tab=box-office">My Penguin Friend</a></b></td>
 <td><a href="/market/distributor/Roadside-Attractions">Roadside Att…</a></td>
 <td class="data">$3,457</td>
 <td class="data chart_down" data-sort="-80">-80%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="62">62</td>
 <td class="data chart_grey" data-sort="56">$56</td>
 <td class="data" data-sort="2727222">$2,727,222</td>
 <td class="data">40</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Tokyo-Cowboy-(2024)#tab=box-office">Tokyo Cowboy</a></b></td>
 <td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>
 <td class="data">$2,284</td>
 <td class="data chart_up" data-sort="102">+102%</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="15">15</td>
 <td class="data chart_grey" data-sort="152">$152</td>
 <td class="data" data-sort="115391">$115,391</td>
 <td class="data">26</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Cowboy-and-the-Queen-The-(2024)#tab=box-office">The Cowboy &amp; the Queen</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$1,592</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="20">20</td>
 <td class="data chart_grey" data-sort="80">$80</td>
 <td class="data" data-sort="35708">$35,708</td>
 <td class="data">19</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Conversation-The#tab=box-office">The Conversation</a></b></td>
 <td><a href="/market/distributor/Rialto-Pictures">Rialto Pictures</a></td>
 <td class="data">$1,358</td>
 <td class="data chart_up" data-sort="4">+4%</td>
 <td class="data chart_down" data-sort="-78">-78%</td>
 <td class="data" data-sort="5">5</td>
 <td class="data chart_grey" data-sort="272">$272</td>
 <td class="data" data-sort="4720809">$4,720,809</td>
 <td class="data">18,434</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Harold-and-the-Purple-Crayon-(2024)#tab=box-office">Harold and the Purple Crayon</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$1,193</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data chart_down" data-sort="-97">-97%</td>
 <td class="data" data-sort="64">64</td>
 <td class="data chart_grey" data-sort="19">$19</td>
 <td class="data" data-sort="17622944">$17,622,944</td>
 <td class="data">54</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Happy-Clothes-A-Film-About-Patricia-Field-(2024)#tab=box-office">Happy Clothes: A Film Abo…</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$754</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1">1</td>
 <td class="data chart_grey" data-sort="754">$754</td>
 <td class="data" data-sort="9442">$9,442</td>
 <td class="data">5</td>
 </tr>
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="37">(37)</td>
 <td><b><a href="/movie/Afraid-(2024)#tab=box-office">Afraid</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$552</td>
 <td class="data chart_down" data-sort="-100">-100%</td>

In [5]:
len(xmas_bo_tables)

2

It turns out there are two tables on the page, the first is a baby table consisting of the "Previous Chart", "Chart Index", and "Next Chart" at the top. We want the second table with all the data: `xmas_bo_tables[1]` returns the second chart (remember that Python is 0-indexed, so the first chart is at `xmas_bo_tables[0]`). With this table identified, we can do a second `find_all` to get the table rows inside it and we save it as `xmas_bo_trs`.

In [6]:
xmas_bo_trs = xmas_bo_tables[1].find_all('tr')

xmas_bo_trs

[<tr><th> </th><th> </th><th>Movie Title</th><th>Distributor</th><th>Gross</th><th>%YD</th><th>%LW</th><th>Theaters</th><th>Per<br/>Theater</th><th>Total<br/>Gross</th><th>Days In<br/>Release</th></tr>,
 <tr>
 <td class="data" data-sort="1">1</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Beetlejuice-Beetlejuice-(2024)#tab=box-office">Beetlejuice Beetlejuice</a></b></td>
 <td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>
 <td class="data">$2,466,902</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="4172">4,172</td>
 <td class="data chart_grey" data-sort="591">$591</td>
 <td class="data" data-sort="230938348">$230,938,348</td>
 <td class="data">19</td>
 </tr>,
 <tr>
 <td class="data" data-sort="2">2</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Transformers-One-(2024)#tab=box-office">Transformers One</a></b></td>
 <td><a href="/market/distributor/Paramount-Pictures">Paramount Pi…</a></td>
 <td class="data">$2,003,977</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="3978">3,978</td>
 <td class="data chart_grey" data-sort="504">$504</td>
 <td class="data" data-sort="27871915">$27,871,915</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="3">3</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Speak-No-Evil-(2024)#tab=box-office">Speak No Evil</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$856,980</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="3375">3,375</td>
 <td class="data chart_grey" data-sort="254">$254</td>
 <td class="data" data-sort="22752895">$22,752,895</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data" data-sort="4">4</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Substance-The-(2024)#tab=box-office">The Substance</a></b></td>
 <td><a href="/market/distributor/MUBI">MUBI</a></td>
 <td class="data">$611,797</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1949">1,949</td>
 <td class="data chart_grey" data-sort="314">$314</td>
 <td class="data" data-sort="4239480">$4,239,480</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="5">5</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Never-Let-Go-(2024)#tab=box-office">Never Let Go</a></b></td>
 <td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>
 <td class="data">$585,690</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="2667">2,667</td>
 <td class="data chart_grey" data-sort="220">$220</td>
 <td class="data" data-sort="5409643">$5,409,643</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="6">6</td>
 <td class="data" data-sort="6">(6)</td>
 <td><b><a href="/movie/Deadpool-and-Wolverine-(2024)#tab=box-office">Deadpool &amp; Wolverine</a></b></td>
 <td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>
 <td class="data">$415,308</td>
 <td class="data chart_down" data-sort="-68">-68%</td>
 <td class="data chart_down" data-sort="-74">-74%</td>
 <td class="data" data-sort="2450">2,450</td>
 <td class="data chart_grey" data-sort="170">$170</td>
 <td class="data" data-sort="627950324">$627,950,324</td>
 <td class="data">61</td>
 </tr>,
 <tr>
 <td class="data chart_up" data-sort="7"><b>7</b></td>
 <td class="data" data-sort="8">(8)</td>
 <td><b><a href="/movie/Reagan-(2024)#tab=box-office">Reagan</a></b></td>
 <td><a href="/market/distributor/ShowBiz-Direct">ShowBiz Direct</a></td>
 <td class="data">$345,565</td>
 <td class="data chart_down" data-sort="-73">-73%</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1850">1,850</td>
 <td class="data chart_grey" data-sort="187">$187</td>
 <td class="data" data-sort="27076790">$27,076,790</td>
 <td class="data">26</td>
 </tr>,
 <tr>
 <td class="data" data-sort="8">8</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Am-I-Racist-(2024)#tab=box-office">Am I Racist?</a></b></td>
 <td><a href="/market/distributor/SDG-Releasing">SDG Releasing</a></td>
 <td class="data">$333,907</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1600">1,600</td>
 <td class="data chart_grey" data-sort="209">$209</td>
 <td class="data" data-sort="9534617">$9,534,617</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data chart_up" data-sort="9"><b>9</b></td>
 <td class="data" data-sort="10">(10)</td>
 <td><b><a href="/movie/Forge-The-(2024)#tab=box-office">The Forge</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$189,784</td>
 <td class="data chart_down" data-sort="-73">-73%</td>
 <td class="data chart_down" data-sort="-71">-71%</td>
 <td class="data" data-sort="1181">1,181</td>
 <td class="data chart_grey" data-sort="161">$161</td>
 <td class="data" data-sort="26637232">$26,637,232</td>
 <td class="data">33</td>
 </tr>,
 <tr>
 <td class="data" data-sort="10">10</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Killers-Game-The-(2024)#tab=box-office">The Killer’s Game</a></b></td>
 <td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>
 <td class="data">$188,157</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="2623">2,623</td>
 <td class="data chart_grey" data-sort="72">$72</td>
 <td class="data" data-sort="5124785">$5,124,785</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data chart_down" data-sort="11">11</td>
 <td class="data" data-sort="9">(9)</td>
 <td><b><a href="/movie/Alien-Romulus-(2024)#tab=box-office">Alien: Romulus</a></b></td>
 <td><a href="/market/distributor/20th-Century-Studios">20th Century…</a></td>
 <td class="data">$186,859</td>
 <td class="data chart_down" data-sort="-81">-81%</td>
 <td class="data chart_down" data-sort="-87">-87%</td>
 <td class="data" data-sort="1350">1,350</td>
 <td class="data chart_grey" data-sort="138">$138</td>
 <td class="data" data-sort="103933623">$103,933,623</td>
 <td class="data">40</td>
 </tr>,
 <tr>
 <td class="data" data-sort="12">12</td>
 <td class="data" data-sort="12">(12)</td>
 <td><b><a href="/movie/It-Ends-With-Us-(2024)#tab=box-office">It Ends With Us</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$152,684</td>
 <td class="data chart_down" data-sort="-82">-82%</td>
 <td class="data chart_down" data-sort="-88">-88%</td>
 <td class="data" data-sort="1164">1,164</td>
 <td class="data chart_grey" data-sort="131">$131</td>
 <td class="data" data-sort="147104126">$147,104,126</td>
 <td class="data">47</td>
 </tr>,
 <tr>
 <td class="data" data-sort="13">13</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Gods-Not-Dead-In-God-We-Trust-(2024)#tab=box-office">God’s Not Dead: In God We…</a></b></td>
 <td><a href="/market/distributor/Fathom-Events">Fathom Events</a></td>
 <td class="data">$89,297</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="444">444</td>
 <td class="data chart_grey" data-sort="201">$201</td>
 <td class="data" data-sort="3196261">$3,196,261</td>
 <td class="data">13</td>
 </tr>,
 <tr>
 <td class="data" data-sort="14">14</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Front-Room-The-(2024)#tab=box-office">The Front Room</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$72,722</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="98">98</td>
 <td class="data chart_grey" data-sort="742">$742</td>
 <td class="data" data-sort="3401469">$3,401,469</td>
 <td class="data">19</td>
 </tr>,
 <tr>
 <td class="data chart_up" data-sort="15"><b>15</b></td>
 <td class="data" data-sort="17">(17)</td>
 <td><b><a href="/movie/Blink-Twice-(2024)#tab=box-office">Blink Twice</a></b></td>
 <td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>
 <td class="data">$54,000</td>
 <td class="data chart_down" data-sort="-92">-92%</td>
 <td class="data chart_down" data-sort="-93">-93%</td>
 <td class="data" data-sort="305">305</td>
 <td class="data chart_grey" data-sort="177">$177</td>
 <td class="data" data-sort="22859926">$22,859,926</td>
 <td class="data">33</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="18">(18)</td>
 <td><b><a href="/movie/Twisters-(2024)#tab=box-office">Twisters</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$53,155</td>
 <td class="data chart_down" data-sort="-93">-93%</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data" data-sort="650">650</td>
 <td class="data chart_grey" data-sort="82">$82</td>
 <td class="data" data-sort="267276205">$267,276,205</td>
 <td class="data">68</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Despicable-Me-4-(2024)#tab=box-office">Despicable Me 4</a></b></td>
 <td><a href="/market/distributor/Universal">Universal</a></td>
 <td class="data">$48,520</td>
 <td class="data chart_down" data-sort="-83">-83%</td>
 <td class="data chart_down" data-sort="-89">-89%</td>
 <td class="data" data-sort="796">796</td>
 <td class="data chart_grey" data-sort="61">$61</td>
 <td class="data" data-sort="360461930">$360,461,930</td>
 <td class="data">84</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/My-Old-Ass-(2024)#tab=box-office">My Old Ass</a></b></td>
 <td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>
 <td class="data">$35,230</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="33">33</td>
 <td class="data chart_grey" data-sort="1068">$1,068</td>
 <td class="data" data-sort="570072">$570,072</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Faith-of-Angels-(2024)#tab=box-office">Faith of Angels</a></b></td>
 <td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>
 <td class="data">$16,129</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="30">30</td>
 <td class="data chart_grey" data-sort="538">$538</td>
 <td class="data" data-sort="174284">$174,284</td>
 <td class="data">13</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Critic-The-(2024)#tab=box-office">The Critic</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$11,818</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="110">110</td>
 <td class="data chart_grey" data-sort="107">$107</td>
 <td class="data" data-sort="379732">$379,732</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Inside-Out-2-(2024)#tab=box-office">Inside Out 2</a></b></td>
 <td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>
 <td class="data">$11,555</td>
 <td class="data chart_down" data-sort="-94">-94%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="250">250</td>
 <td class="data chart_grey" data-sort="46">$46</td>
 <td class="data" data-sort="652894496">$652,894,496</td>
 <td class="data">103</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Dan-Da-Dan-First-Encounter-(2024-Japan)#tab=box-office">DAN DA DAN: First Encounter</a></b></td>
 <td><a href="/market/distributor/GKIDS">GKIDS</a></td>
 <td class="data">$9,838</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="81">81</td>
 <td class="data chart_grey" data-sort="121">$121</td>
 <td class="data" data-sort="1030358">$1,030,358</td>
 <td class="data">12</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Sing-Sing-(2024)#tab=box-office">Sing Sing</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$7,592</td>
 <td class="data" data-sort="0"> </td>
 <td class="data chart_down" data-sort="-80">-80%</td>
 <td class="data" data-sort="35">35</td>
 <td class="data chart_grey" data-sort="217">$217</td>
 <td class="data" data-sort="2733310">$2,733,310</td>
 <td class="data">75</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Trap-(2024)#tab=box-office">Trap</a></b></td>
 <td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>
 <td class="data">$7,466</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="78">78</td>
 <td class="data chart_grey" data-sort="96">$96</td>
 <td class="data" data-sort="42714375">$42,714,375</td>
 <td class="data">54</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Shade-The-(2024)#tab=box-office">The Shade</a></b></td>
 <td><a href="/market/distributor/Level-33">Level 33</a></td>
 <td class="data">$6,595</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="240">240</td>
 <td class="data chart_grey" data-sort="27">$27</td>
 <td class="data" data-sort="54903">$54,903</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Different-Man-A-(2024)#tab=box-office">A Different Man</a></b></td>
 <td><a href="/market/distributor/A24">A24</a></td>
 <td class="data">$5,942</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="4">4</td>
 <td class="data chart_grey" data-sort="1486">$1,486</td>
 <td class="data" data-sort="60687">$60,687</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Didi-(2024)#tab=box-office">Dìdi (弟弟)</a></b></td>
 <td><a href="/market/distributor/Focus-Features">Focus Features</a></td>
 <td class="data">$5,625</td>
 <td class="data chart_down" data-sort="-85">-85%</td>
 <td class="data chart_down" data-sort="-91">-91%</td>
 <td class="data" data-sort="51">51</td>
 <td class="data chart_grey" data-sort="110">$110</td>
 <td class="data" data-sort="4830440">$4,830,440</td>
 <td class="data">61</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Strange-Darling-(2024)#tab=box-office">Strange Darling</a></b></td>
 <td><a href="/market/distributor/Magenta-Light-Studios">Magenta Ligh…</a></td>
 <td class="data">$3,479</td>
 <td class="data chart_down" data-sort="-96">-96%</td>
 <td class="data chart_down" data-sort="-98">-98%</td>
 <td class="data" data-sort="30">30</td>
 <td class="data chart_grey" data-sort="116">$116</td>
 <td class="data" data-sort="3072283">$3,072,283</td>
 <td class="data">33</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/My-Penguin-Friend-(2024)#tab=box-office">My Penguin Friend</a></b></td>
 <td><a href="/market/distributor/Roadside-Attractions">Roadside Att…</a></td>
 <td class="data">$3,457</td>
 <td class="data chart_down" data-sort="-80">-80%</td>
 <td class="data chart_down" data-sort="-95">-95%</td>
 <td class="data" data-sort="62">62</td>
 <td class="data chart_grey" data-sort="56">$56</td>
 <td class="data" data-sort="2727222">$2,727,222</td>
 <td class="data">40</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Tokyo-Cowboy-(2024)#tab=box-office">Tokyo Cowboy</a></b></td>
 <td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>
 <td class="data">$2,284</td>
 <td class="data chart_up" data-sort="102">+102%</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="15">15</td>
 <td class="data chart_grey" data-sort="152">$152</td>
 <td class="data" data-sort="115391">$115,391</td>
 <td class="data">26</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Cowboy-and-the-Queen-The-(2024)#tab=box-office">The Cowboy &amp; the Queen</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$1,592</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="20">20</td>
 <td class="data chart_grey" data-sort="80">$80</td>
 <td class="data" data-sort="35708">$35,708</td>
 <td class="data">19</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Conversation-The#tab=box-office">The Conversation</a></b></td>
 <td><a href="/market/distributor/Rialto-Pictures">Rialto Pictures</a></td>
 <td class="data">$1,358</td>
 <td class="data chart_up" data-sort="4">+4%</td>
 <td class="data chart_down" data-sort="-78">-78%</td>
 <td class="data" data-sort="5">5</td>
 <td class="data chart_grey" data-sort="272">$272</td>
 <td class="data" data-sort="4720809">$4,720,809</td>
 <td class="data">18,434</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Harold-and-the-Purple-Crayon-(2024)#tab=box-office">Harold and the Purple Crayon</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$1,193</td>
 <td class="data chart_down" data-sort="-90">-90%</td>
 <td class="data chart_down" data-sort="-97">-97%</td>
 <td class="data" data-sort="64">64</td>
 <td class="data chart_grey" data-sort="19">$19</td>
 <td class="data" data-sort="17622944">$17,622,944</td>
 <td class="data">54</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/Happy-Clothes-A-Film-About-Patricia-Field-(2024)#tab=box-office">Happy Clothes: A Film Abo…</a></b></td>
 <td><a href="/market/distributor/Greenwich">Greenwich</a></td>
 <td class="data">$754</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="1">1</td>
 <td class="data chart_grey" data-sort="754">$754</td>
 <td class="data" data-sort="9442">$9,442</td>
 <td class="data">5</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="37">(37)</td>
 <td><b><a href="/movie/Afraid-(2024)#tab=box-office">Afraid</a></b></td>
 <td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>
 <td class="data">$552</td>
 <td class="data chart_down" data-sort="-100">-100%</td>
 <td class="data" data-sort="0"> </td>
 <td class="data" data-sort="37">37</td>
 <td class="data chart_grey" data-sort="15">$15</td>
 <td class="data" data-sort="6724923">$6,724,923</td>
 <td class="data">26</td>
 </tr>,
 <tr>
 <td class="data" data-sort="999">-</td>
 <td class="data" data-sort="999">(-)</td>
 <td><b><a href="/movie/War-Game-(2024)#tab=box-office">War Game</a></b></td>

In [7]:
len(xmas_bo_trs)

40

Let's inspect a few of these rows. The first row in our list of rows under `xmas_bo_trs` should be the header with the names of the columns.

In [8]:
xmas_bo_trs[0]

The next table row should be for Aquaman.

In [9]:
xmas_bo_trs[1]

<tr>
<td class="data" data-sort="1">1</td>
<td class="data" data-sort="999">(-)</td>
<td><b><a href="/movie/Beetlejuice-Beetlejuice-(2024)#tab=box-office">Beetlejuice Beetlejuice</a></b></td>
<td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>
<td class="data">$2,466,902</td>
<td class="data" data-sort="0"> </td>
<td class="data" data-sort="0"> </td>
<td class="data" data-sort="4172">4,172</td>
<td class="data chart_grey" data-sort="591">$591</td>
<td class="data" data-sort="230938348">$230,938,348</td>
<td class="data">19</td>
</tr>

If we wanted to access the contents of this table row, we could use the `.contents` method to get a list of each of the `<td>` table cells, which (frustratingly) intersperses newline characters.

In [10]:
xmas_bo_trs[1].contents

['\n',
 <td class="data" data-sort="1">1</td>,
 '\n',
 <td class="data" data-sort="999">(-)</td>,
 '\n',
 <td><b><a href="/movie/Beetlejuice-Beetlejuice-(2024)#tab=box-office">Beetlejuice Beetlejuice</a></b></td>,
 '\n',
 <td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>,
 '\n',
 <td class="data">$2,466,902</td>,
 '\n',
 <td class="data" data-sort="0"> </td>,
 '\n',
 <td class="data" data-sort="0"> </td>,
 '\n',
 <td class="data" data-sort="4172">4,172</td>,
 '\n',
 <td class="data chart_grey" data-sort="591">$591</td>,
 '\n',
 <td class="data" data-sort="230938348">$230,938,348</td>,
 '\n',
 <td class="data">19</td>,
 '\n']

Another alternative is to use the `.text` method to get the text content of all the cells in this row.

In [11]:
xmas_bo_trs[1].text

'\n1\n(-)\nBeetlejuice Beetlejuice\nWarner Bros.\n$2,466,902\n\xa0\n\xa0\n4,172\n$591\n$230,938,348\n19\n'

The `\n` characters re-appear here, but if we `print` out this statement, we see their newline functionality.

In [12]:
print(xmas_bo_trs[1].text)

1
(-)
Beetlejuice Beetlejuice
Warner Bros.
$2,466,902


4,172
$591
$230,938,348
19

We could use string processing to take this text string and convert it into a simple list of data. `.split('\n')` will split the string on the newline characters and return a list of what exists in between.

In [13]:
xmas_bo_trs[1].text.split('\n')

['',
 '1',
 '(-)',
 'Beetlejuice Beetlejuice',
 'Warner Bros.',
 '$2,466,902',
 '\xa0',
 '\xa0',
 '4,172',
 '$591',
 '$230,938,348',
 '19',
 '']

We'll write a `for` loop to go through all the table rows in `xmas_bo_trs`, get the list of data from the row, and add it back to a list of all the rows.

In [14]:
cleaned_xmas_bo_rows = []

# Loop through all the non-header (first row) table rows
for row in xmas_bo_trs[1:]:
    
    # Get the text of the row and split on the newlines (like above)
    cleaned_row = row.text.split('\n')
    
    # Add this cleaned row back to the external list of row data
    cleaned_xmas_bo_rows.append(cleaned_row)
    
# Inspect the first few rows of data
cleaned_xmas_bo_rows[:2]

[['',
  '1',
  '(-)',
  'Beetlejuice Beetlejuice',
  'Warner Bros.',
  '$2,466,902',
  '\xa0',
  '\xa0',
  '4,172',
  '$591',
  '$230,938,348',
  '19',
  ''],
 ['',
  '2',
  '(-)',
  'Transformers One',
  'Paramount Pi…',
  '$2,003,977',
  '\xa0',
  '\xa0',
  '3,978',
  '$504',
  '$27,871,915',
  '5',
  '']]

In [15]:
len(cleaned_xmas_bo_rows)

39

Now we can pass this list of lists in `cleaned_xmas_bo_rows` to pandas's `DataFrame` function and hopefully get a nice table out.

In [16]:
xmas_bo_df = pd.DataFrame(cleaned_xmas_bo_rows)

# Inspect
xmas_bo_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,1,(-),Beetlejuice Beetlejuice,Warner Bros.,"$2,466,902",,,"4,172",$591,"$230,938,348",19,
1,,2,(-),Transformers One,Paramount Pi…,"$2,003,977",,,"3,978",$504,"$27,871,915",5,
2,,3,(-),Speak No Evil,Universal,"$856,980",,,"3,375",$254,"$22,752,895",12,
3,,4,(-),The Substance,MUBI,"$611,797",,,"1,949",$314,"$4,239,480",5,
4,,5,(-),Never Let Go,Lionsgate,"$585,690",,,"2,667",$220,"$5,409,643",5,

We need to do a bit of cleanup on this data:

* Columns 0 and 12 are all empty
* Add column names

In [17]:
# Drop columns 0 and 12 and overwrite the xmas_box_df variable
xmas_bo_df = xmas_bo_df.drop(columns=[0,12])

# Rename the columns
xmas_bo_df.columns = ['Rank','Last rank','Movie','Distributor','Gross',
                      'Change','LW','Theaters','Per theater','Total gross',
                      'Days']

# Write to disk
# xmas_bo_df.to_csv('christmas_2018_box_office.csv',encoding='utf8')

# Inspect
xmas_bo_df.head()

,Rank,Last rank,Movie,Distributor,Gross,Change,LW,Theaters,Per theater,Total gross,Days
0,1,(-),Beetlejuice Beetlejuice,Warner Bros.,"$2,466,902",,,"4,172",$591,"$230,938,348",19
1,2,(-),Transformers One,Paramount Pi…,"$2,003,977",,,"3,978",$504,"$27,871,915",5
2,3,(-),Speak No Evil,Universal,"$856,980",,,"3,375",$254,"$22,752,895",12
3,4,(-),The Substance,MUBI,"$611,797",,,"1,949",$314,"$4,239,480",5
4,5,(-),Never Let Go,Lionsgate,"$585,690",,,"2,667",$220,"$5,409,643",5

### `pandas`'s `read_html`
That was a good amount of work just to get this simple HTML table into Python. But it was important to cover how table elements moved from a string in `requests`, into a soup object from `BeautifulSoup`. into a list of data, and finally into `pandas`. 

`pandas` also has powerful functionality for reading tables directly from HTML. If we convert the soup of the first table (`xmas_bo_tables[1]`) back into a string, `pandas` can read it directly into a table. 

There are a few ideosyncracies here, the result is a list of dataframes—even if there's only a single table/dataframe—so we need to return the first (and only) element of this list. This is why there's a `[0]` at the end and the `.head()` is just to show the first five rows.

In [22]:
str(xmas_bo_tables[1])

'<table class="table-responsive display compact dataTable" id="box_office_daily_table" style="border:none; width:100%">\n<thead><tr><th>\xa0</th><th>\xa0</th><th>Movie Title</th><th>Distributor</th><th>Gross</th><th>%YD</th><th>%LW</th><th>Theaters</th><th>Per<br/>Theater</th><th>Total<br/>Gross</th><th>Days In<br/>Release</th></tr></thead><tbody>\n<tr>\n<td class="data" data-sort="1">1</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Beetlejuice-Beetlejuice-(2024)#tab=box-office">Beetlejuice Beetlejuice</a></b></td>\n<td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>\n<td class="data">$2,466,902</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="4172">4,172</td>\n<td class="data chart_grey" data-sort="591">$591</td>\n<td class="data" data-sort="230938348">$230,938,348</td>\n<td class="data">19</td>\n</tr>\n<tr>\n<td class="data" data-sort="2">2</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Transformers-One-(2024)#tab=box-office">Transformers One</a></b></td>\n<td><a href="/market/distributor/Paramount-Pictures">Paramount Pi…</a></td>\n<td class="data">$2,003,977</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="3978">3,978</td>\n<td class="data chart_grey" data-sort="504">$504</td>\n<td class="data" data-sort="27871915">$27,871,915</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="3">3</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Speak-No-Evil-(2024)#tab=box-office">Speak No Evil</a></b></td>\n<td><a href="/market/distributor/Universal">Universal</a></td>\n<td class="data">$856,980</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="3375">3,375</td>\n<td class="data chart_grey" data-sort="254">$254</td>\n<td class="data" data-sort="22752895">$22,752,895</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data" data-sort="4">4</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Substance-The-(2024)#tab=box-office">The Substance</a></b></td>\n<td><a href="/market/distributor/MUBI">MUBI</a></td>\n<td class="data">$611,797</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="1949">1,949</td>\n<td class="data chart_grey" data-sort="314">$314</td>\n<td class="data" data-sort="4239480">$4,239,480</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="5">5</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Never-Let-Go-(2024)#tab=box-office">Never Let Go</a></b></td>\n<td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>\n<td class="data">$585,690</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="2667">2,667</td>\n<td class="data chart_grey" data-sort="220">$220</td>\n<td class="data" data-sort="5409643">$5,409,643</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="6">6</td>\n<td class="data" data-sort="6">(6)</td>\n<td><b><a href="/movie/Deadpool-and-Wolverine-(2024)#tab=box-office">Deadpool &amp; Wolverine</a></b></td>\n<td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>\n<td class="data">$415,308</td>\n<td class="data chart_down" data-sort="-68">-68%</td>\n<td class="data chart_down" data-sort="-74">-74%</td>\n<td class="data" data-sort="2450">2,450</td>\n<td class="data chart_grey" data-sort="170">$170</td>\n<td class="data" data-sort="627950324">$627,950,324</td>\n<td class="data">61</td>\n</tr>\n<tr>\n<td class="data chart_up" data-sort="7"><b>7</b></td>\n<td class="data" data-sort="8">(8)</td>\n<td><b><a href="/movie/Reagan-(2024)#tab=box-office">Reagan</a></b></td>\n<td><a href="/market/distributor/ShowBiz-Direct">ShowBiz Direct</a></td>\n<td class="data">$345,565</td>\n<td class="data chart_down" data-sort="-73">-73%</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="1850">1,850</td>\n<td class="data chart_grey" data-sort="187">$187</td>\n<td class="data" data-sort="27076790">$27,076,790</td>\n<td class="data">26</td>\n</tr>\n<tr>\n<td class="data" data-sort="8">8</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Am-I-Racist-(2024)#tab=box-office">Am I Racist?</a></b></td>\n<td><a href="/market/distributor/SDG-Releasing">SDG Releasing</a></td>\n<td class="data">$333,907</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="1600">1,600</td>\n<td class="data chart_grey" data-sort="209">$209</td>\n<td class="data" data-sort="9534617">$9,534,617</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data chart_up" data-sort="9"><b>9</b></td>\n<td class="data" data-sort="10">(10)</td>\n<td><b><a href="/movie/Forge-The-(2024)#tab=box-office">The Forge</a></b></td>\n<td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>\n<td class="data">$189,784</td>\n<td class="data chart_down" data-sort="-73">-73%</td>\n<td class="data chart_down" data-sort="-71">-71%</td>\n<td class="data" data-sort="1181">1,181</td>\n<td class="data chart_grey" data-sort="161">$161</td>\n<td class="data" data-sort="26637232">$26,637,232</td>\n<td class="data">33</td>\n</tr>\n<tr>\n<td class="data" data-sort="10">10</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Killers-Game-The-(2024)#tab=box-office">The Killer’s Game</a></b></td>\n<td><a href="/market/distributor/Lionsgate">Lionsgate</a></td>\n<td class="data">$188,157</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="2623">2,623</td>\n<td class="data chart_grey" data-sort="72">$72</td>\n<td class="data" data-sort="5124785">$5,124,785</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data chart_down" data-sort="11">11</td>\n<td class="data" data-sort="9">(9)</td>\n<td><b><a href="/movie/Alien-Romulus-(2024)#tab=box-office">Alien: Romulus</a></b></td>\n<td><a href="/market/distributor/20th-Century-Studios">20th Century…</a></td>\n<td class="data">$186,859</td>\n<td class="data chart_down" data-sort="-81">-81%</td>\n<td class="data chart_down" data-sort="-87">-87%</td>\n<td class="data" data-sort="1350">1,350</td>\n<td class="data chart_grey" data-sort="138">$138</td>\n<td class="data" data-sort="103933623">$103,933,623</td>\n<td class="data">40</td>\n</tr>\n<tr>\n<td class="data" data-sort="12">12</td>\n<td class="data" data-sort="12">(12)</td>\n<td><b><a href="/movie/It-Ends-With-Us-(2024)#tab=box-office">It Ends With Us</a></b></td>\n<td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>\n<td class="data">$152,684</td>\n<td class="data chart_down" data-sort="-82">-82%</td>\n<td class="data chart_down" data-sort="-88">-88%</td>\n<td class="data" data-sort="1164">1,164</td>\n<td class="data chart_grey" data-sort="131">$131</td>\n<td class="data" data-sort="147104126">$147,104,126</td>\n<td class="data">47</td>\n</tr>\n<tr>\n<td class="data" data-sort="13">13</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Gods-Not-Dead-In-God-We-Trust-(2024)#tab=box-office">God’s Not Dead: In God We…</a></b></td>\n<td><a href="/market/distributor/Fathom-Events">Fathom Events</a></td>\n<td class="data">$89,297</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="444">444</td>\n<td class="data chart_grey" data-sort="201">$201</td>\n<td class="data" data-sort="3196261">$3,196,261</td>\n<td class="data">13</td>\n</tr>\n<tr>\n<td class="data" data-sort="14">14</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Front-Room-The-(2024)#tab=box-office">The Front Room</a></b></td>\n<td><a href="/market/distributor/A24">A24</a></td>\n<td class="data">$72,722</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="98">98</td>\n<td class="data chart_grey" data-sort="742">$742</td>\n<td class="data" data-sort="3401469">$3,401,469</td>\n<td class="data">19</td>\n</tr>\n<tr>\n<td class="data chart_up" data-sort="15"><b>15</b></td>\n<td class="data" data-sort="17">(17)</td>\n<td><b><a href="/movie/Blink-Twice-(2024)#tab=box-office">Blink Twice</a></b></td>\n<td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>\n<td class="data">$54,000</td>\n<td class="data chart_down" data-sort="-92">-92%</td>\n<td class="data chart_down" data-sort="-93">-93%</td>\n<td class="data" data-sort="305">305</td>\n<td class="data chart_grey" data-sort="177">$177</td>\n<td class="data" data-sort="22859926">$22,859,926</td>\n<td class="data">33</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="18">(18)</td>\n<td><b><a href="/movie/Twisters-(2024)#tab=box-office">Twisters</a></b></td>\n<td><a href="/market/distributor/Universal">Universal</a></td>\n<td class="data">$53,155</td>\n<td class="data chart_down" data-sort="-93">-93%</td>\n<td class="data chart_down" data-sort="-90">-90%</td>\n<td class="data" data-sort="650">650</td>\n<td class="data chart_grey" data-sort="82">$82</td>\n<td class="data" data-sort="267276205">$267,276,205</td>\n<td class="data">68</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Despicable-Me-4-(2024)#tab=box-office">Despicable Me 4</a></b></td>\n<td><a href="/market/distributor/Universal">Universal</a></td>\n<td class="data">$48,520</td>\n<td class="data chart_down" data-sort="-83">-83%</td>\n<td class="data chart_down" data-sort="-89">-89%</td>\n<td class="data" data-sort="796">796</td>\n<td class="data chart_grey" data-sort="61">$61</td>\n<td class="data" data-sort="360461930">$360,461,930</td>\n<td class="data">84</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/My-Old-Ass-(2024)#tab=box-office">My Old Ass</a></b></td>\n<td><a href="/market/distributor/Amazon-MGM-Studios">Amazon MGM S…</a></td>\n<td class="data">$35,230</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="33">33</td>\n<td class="data chart_grey" data-sort="1068">$1,068</td>\n<td class="data" data-sort="570072">$570,072</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Faith-of-Angels-(2024)#tab=box-office">Faith of Angels</a></b></td>\n<td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>\n<td class="data">$16,129</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="30">30</td>\n<td class="data chart_grey" data-sort="538">$538</td>\n<td class="data" data-sort="174284">$174,284</td>\n<td class="data">13</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Critic-The-(2024)#tab=box-office">The Critic</a></b></td>\n<td><a href="/market/distributor/Greenwich">Greenwich</a></td>\n<td class="data">$11,818</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="110">110</td>\n<td class="data chart_grey" data-sort="107">$107</td>\n<td class="data" data-sort="379732">$379,732</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Inside-Out-2-(2024)#tab=box-office">Inside Out 2</a></b></td>\n<td><a href="/market/distributor/Walt-Disney">Walt Disney</a></td>\n<td class="data">$11,555</td>\n<td class="data chart_down" data-sort="-94">-94%</td>\n<td class="data chart_down" data-sort="-95">-95%</td>\n<td class="data" data-sort="250">250</td>\n<td class="data chart_grey" data-sort="46">$46</td>\n<td class="data" data-sort="652894496">$652,894,496</td>\n<td class="data">103</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Dan-Da-Dan-First-Encounter-(2024-Japan)#tab=box-office">DAN DA DAN: First Encounter</a></b></td>\n<td><a href="/market/distributor/GKIDS">GKIDS</a></td>\n<td class="data">$9,838</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="81">81</td>\n<td class="data chart_grey" data-sort="121">$121</td>\n<td class="data" data-sort="1030358">$1,030,358</td>\n<td class="data">12</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Sing-Sing-(2024)#tab=box-office">Sing Sing</a></b></td>\n<td><a href="/market/distributor/A24">A24</a></td>\n<td class="data">$7,592</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data chart_down" data-sort="-80">-80%</td>\n<td class="data" data-sort="35">35</td>\n<td class="data chart_grey" data-sort="217">$217</td>\n<td class="data" data-sort="2733310">$2,733,310</td>\n<td class="data">75</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Trap-(2024)#tab=box-office">Trap</a></b></td>\n<td><a href="/market/distributor/Warner-Bros">Warner Bros.</a></td>\n<td class="data">$7,466</td>\n<td class="data chart_down" data-sort="-90">-90%</td>\n<td class="data chart_down" data-sort="-95">-95%</td>\n<td class="data" data-sort="78">78</td>\n<td class="data chart_grey" data-sort="96">$96</td>\n<td class="data" data-sort="42714375">$42,714,375</td>\n<td class="data">54</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Shade-The-(2024)#tab=box-office">The Shade</a></b></td>\n<td><a href="/market/distributor/Level-33">Level 33</a></td>\n<td class="data">$6,595</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="240">240</td>\n<td class="data chart_grey" data-sort="27">$27</td>\n<td class="data" data-sort="54903">$54,903</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Different-Man-A-(2024)#tab=box-office">A Different Man</a></b></td>\n<td><a href="/market/distributor/A24">A24</a></td>\n<td class="data">$5,942</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="4">4</td>\n<td class="data chart_grey" data-sort="1486">$1,486</td>\n<td class="data" data-sort="60687">$60,687</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Didi-(2024)#tab=box-office">Dìdi (弟弟)</a></b></td>\n<td><a href="/market/distributor/Focus-Features">Focus Features</a></td>\n<td class="data">$5,625</td>\n<td class="data chart_down" data-sort="-85">-85%</td>\n<td class="data chart_down" data-sort="-91">-91%</td>\n<td class="data" data-sort="51">51</td>\n<td class="data chart_grey" data-sort="110">$110</td>\n<td class="data" data-sort="4830440">$4,830,440</td>\n<td class="data">61</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Strange-Darling-(2024)#tab=box-office">Strange Darling</a></b></td>\n<td><a href="/market/distributor/Magenta-Light-Studios">Magenta Ligh…</a></td>\n<td class="data">$3,479</td>\n<td class="data chart_down" data-sort="-96">-96%</td>\n<td class="data chart_down" data-sort="-98">-98%</td>\n<td class="data" data-sort="30">30</td>\n<td class="data chart_grey" data-sort="116">$116</td>\n<td class="data" data-sort="3072283">$3,072,283</td>\n<td class="data">33</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/My-Penguin-Friend-(2024)#tab=box-office">My Penguin Friend</a></b></td>\n<td><a href="/market/distributor/Roadside-Attractions">Roadside Att…</a></td>\n<td class="data">$3,457</td>\n<td class="data chart_down" data-sort="-80">-80%</td>\n<td class="data chart_down" data-sort="-95">-95%</td>\n<td class="data" data-sort="62">62</td>\n<td class="data chart_grey" data-sort="56">$56</td>\n<td class="data" data-sort="2727222">$2,727,222</td>\n<td class="data">40</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Tokyo-Cowboy-(2024)#tab=box-office">Tokyo Cowboy</a></b></td>\n<td><a href="/market/distributor/Purdie-Distribution">Purdie Distr…</a></td>\n<td class="data">$2,284</td>\n<td class="data chart_up" data-sort="102">+102%</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="15">15</td>\n<td class="data chart_grey" data-sort="152">$152</td>\n<td class="data" data-sort="115391">$115,391</td>\n<td class="data">26</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Cowboy-and-the-Queen-The-(2024)#tab=box-office">The Cowboy &amp; the Queen</a></b></td>\n<td><a href="/market/distributor/Greenwich">Greenwich</a></td>\n<td class="data">$1,592</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="20">20</td>\n<td class="data chart_grey" data-sort="80">$80</td>\n<td class="data" data-sort="35708">$35,708</td>\n<td class="data">19</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Conversation-The#tab=box-office">The Conversation</a></b></td>\n<td><a href="/market/distributor/Rialto-Pictures">Rialto Pictures</a></td>\n<td class="data">$1,358</td>\n<td class="data chart_up" data-sort="4">+4%</td>\n<td class="data chart_down" data-sort="-78">-78%</td>\n<td class="data" data-sort="5">5</td>\n<td class="data chart_grey" data-sort="272">$272</td>\n<td class="data" data-sort="4720809">$4,720,809</td>\n<td class="data">18,434</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Harold-and-the-Purple-Crayon-(2024)#tab=box-office">Harold and the Purple Crayon</a></b></td>\n<td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>\n<td class="data">$1,193</td>\n<td class="data chart_down" data-sort="-90">-90%</td>\n<td class="data chart_down" data-sort="-97">-97%</td>\n<td class="data" data-sort="64">64</td>\n<td class="data chart_grey" data-sort="19">$19</td>\n<td class="data" data-sort="17622944">$17,622,944</td>\n<td class="data">54</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="999">(-)</td>\n<td><b><a href="/movie/Happy-Clothes-A-Film-About-Patricia-Field-(2024)#tab=box-office">Happy Clothes: A Film Abo…</a></b></td>\n<td><a href="/market/distributor/Greenwich">Greenwich</a></td>\n<td class="data">$754</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="1">1</td>\n<td class="data chart_grey" data-sort="754">$754</td>\n<td class="data" data-sort="9442">$9,442</td>\n<td class="data">5</td>\n</tr>\n<tr>\n<td class="data" data-sort="999">-</td>\n<td class="data" data-sort="37">(37)</td>\n<td><b><a href="/movie/Afraid-(2024)#tab=box-office">Afraid</a></b></td>\n<td><a href="/market/distributor/Sony-Pictures">Sony Pictures</a></td>\n<td class="data">$552</td>\n<td class="data chart_down" data-sort="-100">-100%</td>\n<td class="data" data-sort="0">\xa0</td>\n<td class="data" data-sort="37">37</td>\n<td class="data chart_grey" data-sort="15">$15</td>\n<td class="data" data-sort="6724923">$6,724,923</td>\

In [24]:
xmas_bo_table_as_string = str(xmas_bo_tables[1])

pd.read_html(xmas_bo_table_as_string)[0]

/var/folders/lr/v195xr617d32k2zdwwh30sb40000gn/T/ipykernel_57110/1286638848.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(xmas_bo_table_as_string)[0]

,Unnamed: 0,Unnamed: 1,Movie Title,Distributor,Gross,%YD,%LW,Theaters,Per Theater,Total Gross,Days In Release
0,1,(-),Beetlejuice Beetlejuice,Warner Bros.,"$2,466,902",NaN,NaN,4172.0,$591,"$230,938,348",19.0
1,2,(-),Transformers One,Paramount Pi…,"$2,003,977",NaN,NaN,3978.0,$504,"$27,871,915",5.0
2,3,(-),Speak No Evil,Universal,"$856,980",NaN,NaN,3375.0,$254,"$22,752,895",12.0
3,4,(-),The Substance,MUBI,"$611,797",NaN,NaN,1949.0,$314,"$4,239,480",5.0
4,5,(-),Never Let Go,Lionsgate,"$585,690",NaN,NaN,2667.0,$220,"$5,409,643",5.0
5,6,(6),Deadpool & Wolverine,Walt Disney,"$415,308",-68%,-74%,2450.0,$170,"$627,950,324",61.0
6,7,(8),Reagan,ShowBiz Direct,"$345,565",-73%,NaN,1850.0,$187,"$27,076,790",26.0
7,8,(-),Am I Racist?,SDG Releasing,"$333,907",NaN,NaN,1600.0,$209,"$9,534,617",12.0
8,9,(10),The Forge,Sony Pictures,"$189,784",-73%,-71%,1181.0,$161,"$26,637,232",33.0
9,10,(-),The Killer’s Game,Lionsgate,"$188,157",NaN,NaN,2623.0,$72,"$5,124,785",12.0
10,11,(9),Alien: Romulus,20th Century…,"$186,859",-81%,-87%,1350.0,$138,"$103,933,623",40.0
11,12,(12),It Ends With Us,Sony Pictures,"$152,684",-82%,-88%,1164.0,$131,"$147,104,126",47.0
12,13,(-),God’s Not Dead: In God We…,Fathom Events,"$89,297",NaN,NaN,444.0,$201,"$3,196,261",13.0
13,14,(-),The Front Room,A24,"$72,722",NaN,NaN,98.0,$742,"$3,401,469",19.0
14,15,(17),Blink Twice,Amazon MGM S…,"$54,000",-92%,-93%,305.0,$177,"$22,859,926",33.0
15,-,(18),Twisters,Universal,"$53,155",-93%,-90%,650.0,$82,"$267,276,205",68.0
16,-,(-),Despicable Me 4,Universal,"$48,520",-83%,-89%,796.0,$61,"$360,461,930",84.0
17,-,(-),My Old Ass,Amazon MGM S…,"$35,230",NaN,NaN,33.0,"$1,068","$570,072",12.0
18,-,(-),Faith of Angels,Purdie Distr…,"$16,129",NaN,NaN,30.0,$538,"$174,284",13.0
19,-,(-),The Critic,Greenwich,"$11,818",NaN,NaN,110.0,$107,"$379,732",12.0
20,-,(-),Inside Out 2,Walt Disney,"$11,555",-94%,-95%,250.0,$46,"$652,894,496",103.0
21,-,(-),DAN DA DAN: First Encounter,GKIDS,"$9,838",NaN,NaN,81.0,$121,"$1,030,358",12.0
22,-,(-),Sing Sing,A24,"$7,592",NaN,-80%,35.0,$217,"$2,733,310",75.0
23,-,(-),Trap,Warner Bros.,"$7,466",-90%,-95%,78.0,$96,"$42,714,375",54.0
24,-,(-),The Shade,Level 33,"$6,595",NaN,NaN,240.0,$27,"$54,903",5.0
25,-,(-),A Different Man,A24,"$5,942",NaN,NaN,4.0,"$1,486","$60,687",5.0
26,-,(-),Dìdi (弟弟),Focus Features,"$5,625",-85%,-91%,51.0,$110,"$4,830,440",61.0
27,-,(-),Strange Darling,Magenta Ligh…,"$3,479",-96%,-98%,30.0,$116,"$3,072,283",33.0
28,-,(-),My Penguin Friend,Roadside Att…,"$3,457",-80%,-95%,62.0,$56,"$2,727,222",40.0
29,-,(-),Tokyo Cowboy,Purdie Distr…,"$2,284",+102%,NaN,15.0,$152,"$115,391",26.0
30,-,(-),The Cowboy & the Queen,Greenwich,"$1,592",NaN,NaN,20.0,$80,"$35,708",19.0
31,-,(-),The Conversation,Rialto Pictures,"$1,358",+4%,-78%,5.0,$272,"$4,720,809",18434.0
32,-,(-),Harold and the Purple Crayon,Sony Pictures,"$1,193",-90%,-97%,64.0,$19,"$17,622,944",54.0
33,-,(-),Happy Clothes: A Film Abo…,Greenwich,$754,NaN,NaN,1.0,$754,"$9,442",5.0
34,-,(37),Afraid,Sony Pictures,$552,-100%,NaN,37.0,$15,"$6,724,923",26.0
35,-,(-),War Game,Submarine De…,$384,NaN,NaN,3.0,$128,"$107,338",54.0
36,-,(-),City of Dreams,Roadside Att…,$78,-100%,NaN,3.0,$26,"$1,713,278",26.0
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,37,NaN,"$8,788,225",NaN,NaN,NaN,NaN,NaN,NaN

The column names got lumped in as rows, but we can fix this as well with the `read_html` function by passing the row index where the column lives. In this case, it is the first row, so we pass `header=0`.

In [ ]:
pd.read_html(xmas_bo_table_as_string,header=0)[0].head()

Finally, you can point `read_html` at a URL without any `requests` or `BeautifulSoup` and get all the tables on the page as a list of DataFrames. `pandas` is simply doing the `requests` and `BeautifulSoup` on the inside. Interestingly, I'm getting a [HTTP 403](https://en.wikipedia.org/wiki/HTTP_403) error indicating the server (The Numbers) is forbidding the client (us) from accessing their data using this strategy. We will discuss next week whether and how to handle situations where web servers refuse connections from non-human clients. In this case, you cannot use the off-the-shelf `read_html` approach and would need to revert to using the `requests`+`BeautifulSoup` approach above.

In [25]:
simple_tables = pd.read_html(
    'https://www.the-numbers.com/box-office-chart/daily/2018/12/25',
)
simple_tables

HTTPError: HTTP Error 403: Forbidden

If we point it at Wikipedia's [2018 in film](https://en.wikipedia.org/wiki/2018_in_film), it will pull all of the tables present on the page.

In [26]:
simple_tables = pd.read_html('https://en.wikipedia.org/wiki/2018_in_film')
len(simple_tables)

9

The first three correspond to the "Year in film" navigation box on the side and are poorly-formatted by default.

In [30]:
simple_tables[3]

,Rank,Title,Distributor,Worldwide gross
0,1,Avengers: Infinity War,Disney,"$2,048,359,754"
1,2,Black Panther,Disney,"$1,347,597,973"
2,3,Jurassic World: Fallen Kingdom,Universal,"$1,308,467,944"
3,4,Incredibles 2,Disney,"$1,242,805,359"
4,5,Aquaman,Warner Bros.,"$1,148,528,393"
5,6,Bohemian Rhapsody,20th Century Fox,"$910,809,311"
6,7,Venom,Sony,"$856,085,151"
7,8,Mission: Impossible – Fallout,Paramount,"$791,115,104"
8,9,Deadpool 2,20th Century Fox,"$785,896,609"
9,10,Fantastic Beasts: The Crimes of Grindelwald,Warner Bros.,"$654,855,901"

The fourth table in the `simple_tables` list we got from parsing the Wikipedia page with `read_html` is the table under the "Highest-grossing films" section.

In [ ]:
simple_tables[3]

You can pass the "header" option in `read_html` to make sure the column names from a particular row (in this case the first row) do not accidentally become rows of data.

In [31]:
wiki_top_grossing_t = pd.read_html('https://en.wikipedia.org/wiki/2018_in_film',header=0)[3]
wiki_top_grossing_t

,Rank,Title,Distributor,Worldwide gross
0,1,Avengers: Infinity War,Disney,"$2,048,359,754"
1,2,Black Panther,Disney,"$1,347,597,973"
2,3,Jurassic World: Fallen Kingdom,Universal,"$1,308,467,944"
3,4,Incredibles 2,Disney,"$1,242,805,359"
4,5,Aquaman,Warner Bros.,"$1,148,528,393"
5,6,Bohemian Rhapsody,20th Century Fox,"$910,809,311"
6,7,Venom,Sony,"$856,085,151"
7,8,Mission: Impossible – Fallout,Paramount,"$791,115,104"
8,9,Deadpool 2,20th Century Fox,"$785,896,609"
9,10,Fantastic Beasts: The Crimes of Grindelwald,Warner Bros.,"$654,855,901"

In [32]:
wiki_top_grossing_t['Worldwide gross']

0    $2,048,359,754
1    $1,347,597,973
2    $1,308,467,944
3    $1,242,805,359
4    $1,148,528,393
5      $910,809,311
6      $856,085,151
7      $791,115,104
8      $785,896,609
9      $654,855,901
Name: Worldwide gross, dtype: object

Note that there are still a few errors in this table because the "Disney" value in the Wikipedia table spans two rows and `read_html` thus skips the "Distributor" value for Black Panther.

In [ ]:
# Copy the value at index position 1, column position Distributor to Wordwide gross
wiki_top_grossing_t.loc[1,'Worldwide gross'] = wiki_top_grossing_t.loc[1,'Distributor']

# Change the value at 1, Distributor to Disney
wiki_top_grossing_t.loc[1,'Distributor'] = 'Disney'

wiki_top_grossing_t

### Exercise 01

Grab a table from Wikipedia using pandas `read_html`.

In [38]:
wiki_mountains = pd.read_html('https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth')

wiki_mountains[1]

,Rank[i],Mountain name(s),Height (rounded)[ii],Prominence (rounded)[iii],Range,Coordinates[iv],Parent mountain [v],First ascent[vi],Country,Photo
0,1,Mount EverestSagarmathaChomolungma,"8,849 metres (29,032 ft) [a]","8,849 metres (29,032 ft)",Mahalangur Himalaya,27°59′17″N 86°55′30″E﻿ / ﻿27.9881°N 86.925°E,—,1953,NepalChina,NaN
1,2,K2,"8,611 metres (28,251 ft)","4,020 metres (13,190 ft)",Baltoro Karakoram,35°52′53″N 76°30′48″E﻿ / ﻿35.88139°N 76.51333°E,Mount Everest,1954,Pakistan[b]China[16],NaN
2,3,Kangchenjunga,"8,586 metres (28,169 ft)","3,922 metres (12,867 ft)",Kangchenjunga Himalaya,27°42′12″N 88°08′51″E﻿ / ﻿27.70333°N 88.14750°E *,Mount Everest,1955,NepalIndia,NaN
3,4,Lhotse,"8,516 metres (27,940 ft)","610 metres (2,000 ft)",Mahalangur Himalaya,27°57′42″N 86°55′59″E﻿ / ﻿27.96167°N 86.93306°E,Mount Everest,1956,ChinaNepal,NaN
4,5,Makalu,"8,485 metres (27,838 ft)","2,378 metres (7,802 ft)",Mahalangur Himalaya,27°53′23″N 87°05′20″E﻿ / ﻿27.88972°N 87.08889°E,Mount Everest,1955,NepalChina,NaN
...,...,...,...,...,...,...,...,...,...,...
115,104,Noijin KangsangNorin Kang,"7,206 metres (23,642 ft)","2,160 metres (7,090 ft)",Nagarze Himalaya,28°56′48″N 90°10′42″E﻿ / ﻿28.94667°N 90.17833°E,Gangkhar Puensum,1986,China,NaN
116,105,Langtang Ri,"7,205 metres (23,638 ft)","665 metres (2,182 ft)",Langtang Himalaya,28°22′53″N 85°41′01″E﻿ / ﻿28.38139°N 85.68361°E,Shishapangma,1981,NepalChina,NaN
117,106,Kangphu KangShimokangri,"7,204 metres (23,635 ft)","1,244 metres (4,081 ft)",Lunana Himalaya,28°09′24″N 90°04′15″E﻿ / ﻿28.15667°N 90.07083°E,Tongshanjiabu,2002,BhutanChina[k],NaN
118,107,Singhi Kangri,"7,202 metres (23,629 ft)","730 metres (2,400 ft)",Siachen Karakoram,35°35′59″N 76°59′01″E﻿ / ﻿35.59972°N 76.98361°E,Teram Kangri III,1976,IndiaChina[g][h][f],NaN
119,108,Lupghar Sar,"7,200 metres (23,600 ft)","730 metres (2,400 ft)",Hispar Karakoram,36°21′01″N 75°02′13″E﻿ / ﻿36.35028°N 75.03694°E *,Momhil Sar,1979,Pakistan[b],NaN

In [34]:
got_s8_tables[1]

,No. overall,No. in season,Title,Directed by,Written by,Original air date [2],U.S. viewers (millions),Unnamed: 7
0,68,1,"""Winterfell""",David Nutter,Dave Hill,"April 14, 2019",11.76[3],NaN
1,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...,Upon reaching Winterfell with their combined a...
2,69,2,"""A Knight of the Seven Kingdoms""",David Nutter,Bryan Cogman,"April 21, 2019",10.29[4],NaN
3,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...,Jaime reveals Cersei's deception to the Targar...
4,70,3,"""The Long Night""",Miguel Sapochnik,David Benioff & D. B. Weiss,"April 28, 2019",12.02[5],NaN
5,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...,The living meet the Army of the Dead outside W...
6,71,4,"""The Last of the Starks""",David Nutter,David Benioff & D. B. Weiss,"May 5, 2019",11.80[6],NaN
7,"The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c...","The survivors mourn, burn the dead, and then c..."
8,72,5,"""The Bells""",Miguel Sapochnik,David Benioff & D. B. Weiss,"May 12, 2019",12.48[7],NaN
9,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...,Varys urges Jon to advance his claim to the th...
10,73,6,"""The Iron Throne""",David Benioff & D. B. Weiss,David Benioff & D. B. Weiss,"May 19, 2019",13.61[8],NaN
11,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...,Jon is appalled when the Unsullied execute cap...

## Writing your own parser

We will return to the historical Oscars data. Even though data as prominent as this is likely to already exist in tabular format somewhere, we will maintain the illusion that we are the first to both scrape it and parse it into a tabular format. Our goal here is to write a parser that will (ideally) work across multiple pages; in this case, each of the award years.

One of the first things we should do before writing any code is come up with a model of what we want our data to look like at the end of this. This is an intuitive and "tidy" format, but you might come up with alternatives based on your analysis and modeling needs.

| *Year* | *Category* | *Nominee* | *Movie* | *Won* |
| --- | --- | --- | --- | --- |
| 2019 | Actor in a leading role | Christian Bale | Vice | NA |
| 2019 | Actor in a leading role | Bradley Cooper | A Star Is Born | NA |
| 2019 | Actor in a leading role | Willem Dafoe | At Eternity's Gate | NA |
| 2019 | Actor in a leading role | Rami Malek | Bohemian Rhapsody | NA |
| 2019 | Actor in a leading role | Viggo Mortensen | Green Book | NA |

We will begin with writing a parser for a (hopefully!) representative year, then scrape the data for all the years, then apply the scraper to each of those years, and finally combine all the years' data together into a large data set. 

Let's begin with writing a parser for a (hopefully!) representative year. We will use 2018 instead and make the profoundly naïve assumption it should work the same going back in time.

Start off with using `requests` to get the data and then use `BeautifulSoup` to turn it into soup we can parse through.

In [39]:
user_agent

{'user-agent': 'info-5871/0.0 Web Data Science, brian.keegan@colorado.edu'}

Using the Inspect tool exercise from Class 1, the `<div class="view-grouping">` seems to be the most promising tag for us to extract. Use `.find_all('div',{'class':'field__item'})` to (hopefully!) get all of these award groups. Inspect the first and last ones to make sure they looks coherent.

In [40]:
oscars_raw = requests.get('https://www.oscars.org/oscars/ceremonies/2024',headers=user_agent).text

oscars_soup = BeautifulSoup(oscars_raw)

In [41]:
# Get all the groups that have a <div class="view-grouping"> tag
oscars_groups = oscars_soup.find_all('div',{'class':'field__item'})

# Inspect the first one
oscars_groups[0]

The last group is something besides "Writing (Original Screenplay)" and it's not clear to me where this tag's content renders on the page.

In [42]:
# Inspect the last one
oscars_groups[-1]

This puts us into something of a bind going forward: if the `.find_all` returns more groupings than we expected, then it's not sufficiently precise to identify *only* groupings of nominees.  However, there do not appear to be any child tags in the `oscars2018_groups[0]` grouping that uniquely differentiate them from the child tags present in the `oscars2018_groups[-1]` grouping. Another alternative is to simple parse the first 24 groupings, but this is a very brittle solution since other years' awards might have more or fewer groupings.

In [43]:
len(oscars_groups)

432

### Navigating the HTML tree to find more specific parent elements
A third alternative is to leverage the tree structure of HTML and get the parent element in the hopes it is more unique than its children. In this case something like `<div class="field field--name-field-award-categories field--type-entity-reference-revisions field--label-hidden field__items"...>` is a promising lead. Use `find_all` to search for this tag and confirm there is only one the one `<div>` element (with its children) rather than multiple `<div>` elements matching "quicktabs-container-honorees".

In [44]:
# Get the new tag group
oscars_parent_group = oscars_soup.find_all('div',{'class':'field field--name-field-award-categories field--type-entity-reference-revisions field--label-hidden field__items'})

# Hopefully there is only one group matching this pattern
len(oscars_parent_group)

1

So far so good, now we can use `find_all` on the soup for this `<div class="field__item">` to search *within* this specific parent group and hopefully there should be the 24 awards groupings. Nope, still lots.

In [45]:
# Note the addition of the [0] since the _parent_group is a list with 1 element in it
# We just extract that single element (which is a soup) and then we can use find_all on it

oscars_child_groups = oscars_parent_group[0].find_all('div',{'class':'field__item'})

len(oscars_child_groups)

406

Hallelujah! The award names for each group live inside a `<div class="field field--name-field-award-honorees field--type-entity-reference-revisions field--label-hidden field__items">`, so we can `find_all` for those, loop through each, and print out the name.

In [46]:
oscars_award_groups = oscars_parent_group[0].find_all('div',{'class':'paragraph paragraph--type--award-category paragraph--view-mode--default'})
len(oscars_award_groups)

23

In [47]:
for group in oscars_award_groups:
    print(group.text)

Actor in a Leading Role



Winner


Cillian Murphy



Oppenheimer





Nominees


Bradley Cooper



Maestro





Nominees


Colman Domingo



Rustin





Nominees


Paul Giamatti



The Holdovers





Nominees


Jeffrey Wright



American Fiction






Actor in a Supporting Role



Winner


Robert Downey Jr.



Oppenheimer





Nominees


Sterling K. Brown



American Fiction





Nominees


Robert De Niro



Killers of the Flower Moon





Nominees


Ryan Gosling



Barbie





Nominees


Mark Ruffalo



Poor Things






Actress in a Leading Role



Winner


Emma Stone



Poor Things





Nominees


Annette Bening



Nyad





Nominees


Lily Gladstone



Killers of the Flower Moon





Nominees


Sandra Hüller



Anatomy of a Fall





Nominees


Carey Mulligan



Maestro






Actress in a Supporting Role



Winner


Da'Vine Joy Randolph



The Holdovers





Nominees


Emily Blunt



Oppenheimer





Nominees


Danielle Brooks



The Color Purple





Nominees


America Ferrera



Barbie





Nominees


Jodie Foster



Nyad






Animated Feature Film



Winner

The Boy and the Heron



Hayao Miyazaki and Toshio Suzuki






Nominees

Elemental



Peter Sohn and Denise Ream






Nominees

Nimona



Nick Bruno, Troy Quane, Karen Ryan and Julie Zackary






Nominees

Robot Dreams



Pablo Berger, Ibon Cormenzana, Ignasi Estapé and Sandra Tapia Díaz






Nominees

Spider-Man: Across the Spider-Verse



Kemp Powers, Justin K. Thompson, Phil Lord, Christopher Miller and Amy Pascal







Cinematography



Winner

Oppenheimer



Hoyte van Hoytema






Nominees

El Conde



Edward Lachman






Nominees

Killers of the Flower Moon



Rodrigo Prieto






Nominees

Maestro



Matthew Libatique






Nominees

Poor Things



Robbie Ryan







Costume Design



Winner

Poor Things



Holly Waddington






Nominees

Barbie



Jacqueline Durran






Nominees

Killers of the Flower Moon



Jacqueline West






Nominees

Napoleon



Janty Yates and Dave Crossman






Nominees

Oppenheimer



Ellen Mirojnick







Directing



Winner

Oppenheimer



Christopher Nolan






Nominees

Anatomy of a Fall



Justine Triet






Nominees

Killers of the Flower Moon



Martin Scorsese






Nominees

Poor Things



Yorgos Lanthimos






Nominees

The Zone of Interest



Jonathan Glazer







Documentary Feature Film



Winner

20 Days in Mariupol



Mstyslav Chernov, Michelle Mizner and Raney Aronson-Rath






Nominees

Bobi Wine: The People's President



Moses Bwayo, Christopher Sharp and John Battsek






Nominees

The Eternal Memory



Maite Alberdi






Nominees

Four Daughters



Kaouther Ben Hania and Nadim Cheikhrouha






Nominees

To Kill a Tiger



Nisha Pahuja, Cornelia Principe and David Oppenheim







Documentary Short Film



Winner

The Last Repair Shop



Ben Proudfoot and Kris Bowers






Nominees

The ABCs of Book Banning



Sheila Nevins and Trish Adlesic






Nominees

The Barber of Little Rock



John Hoffman and Christine Turner






Nominees

Island in Between



S. Leo Chiang and Jean Tsien






Nominees

Nǎi Nai & Wài Pó



Sean Wang and Sam Davis







Film Editing



Winner

Oppenheimer



Jennifer Lame






Nominees

Anatomy of a Fall



Laurent Sénéchal






Nominees

The Holdovers



Kevin Tent






Nominees

Killers of the Flower Moon



Thelma Schoonmaker






Nominees

Poor Things



Yorgos Mavropsaridis







International Feature Film



Winner

United Kingdom



The Zone of Interest






Nominees

Italy



Io Capitano






Nominees

Japan



Perfect Days






Nominees

Spain



Society of the Snow






Nominees

Germany



The Teachers' Lounge







Makeup and Hairstyling



Winner

Poor Things



Nadia Stacey, Mark Coulier and Josh Weston






Nominees

Golda



Karen Hartley Thomas, Suzi Battersby and Ashra Kelly-Blue






Nominees

Maestro



Kazu Hiro, Kay Georgiou and Lori McCoy-Bell






Nominees

Oppenheimer



Luisa Abel






Nominees

Society of the Snow



Ana López-Puigcerver, David Martí and Montse Ribé







Music (Original Score)



Winner

Oppenheimer



Ludwig Göransson






Nominees

American Fiction



Laura Karpman






Nominees

Indiana Jones and the Dial of Destiny



John Williams






Nominees

Killers of the Flower Moon



Robbie Robertson






Nominees

Poor Things



Jerskin Fendrix







Music (Original Song)



Winner

What Was I Made For?



from Barbie; Music and Lyric by Billie Eilish and Finneas O'Connell






Nominees

The Fire Inside



from Flamin' Hot; Music and Lyric by Diane Warren






Nominees

I'm Just Ken



from Barbie; Music and Lyric by Mark Ronson and Andrew Wyatt






Nominees

It Never Went Away



from American Symphony; Music and Lyric by Jon Batiste and Dan Wilson






Nominees

Wahzhazhe (A Song For My People)



from Killers of the Flower Moon; Music and Lyric by Scott George







Best Picture



Winner

Oppenheimer



Emma Thomas, Charles Roven and Christopher Nolan, Producers






Nominees

American Fiction



Ben LeClair, Nikos Karamigios, Cord Jefferson and Jermaine Johnson, Producers






Nominees

Anatomy of a Fall



Marie-Ange Luciani and David Thion, Producers






Nominees

Barbie



David Heyman, Margot Robbie, Tom Ackerley and Robbie Brenner, Producers






Nominees

The Holdovers



Mark Johnson, Producer






Nominees

Killers of the Flower Moon



Dan Friedkin, Bradley Thomas, Martin Scorsese and Daniel Lupi, Producers






Nominees

Maestro



Bradley Cooper, Steven Spielberg, Fred Berner, Amy Durning and Kristie Macosko Krieger, Producers






Nominees

Past Lives



David Hinojosa, Christine Vachon and Pamela Koffler, Producers






Nominees

Poor Things



Ed Guiney, Andrew Lowe, Yorgos Lanthimos and Emma Stone, Producers






Nominees

The Zone of Interest



James Wilson, Producer







Production Design



Winner

Poor Things



Production Design: James Price and Shona Heath; Set Decoration: Zsuzsa Mihalek






Nominees

Barbie



Production Design: Sarah Greenwood; Set Decoration: Katie Spencer






Nominees

Killers of the Flower Moon



Production Design: Jack Fisk; Set Decoration: Adam Willis






Nominees

Napoleon



Production Design: Arthur Max; Set Decoration: Elli Griff






Nominees

Oppenheimer



Production Design: Ruth De Jong; Set Decoration: Claire Kaufman







Animated Short Film



Winner

WAR IS OVER! Inspired by the Music of John & Yoko



Dave Mullins and Brad Booker






Nominees

Letter to a Pig



Tal Kantor and Amit R. Gicelter






Nominees

Ninety-Five Senses



Jerusha Hess and Jared Hess






Nominees

Our Uniform



Yegane Moghaddam






Nominees

Pachyderme



Stéphanie Clément and Marc Rius







Live Action Short Film



Winner

The Wonderful Story of Henry Sugar



Wes Anderson and Steven Rales






Nominees

The After



Misan Harriman and Nicky Bentham






Nominees

Invincible



Vincent René-Lortie and Samuel Caron






Nominees

Knight of Fortune



Lasse Lyskjær Noer and Christian Norlyk






Nominees

Red, White and Blue



Nazrin Choudhury and Sara McFarlane







Sound



Winner

The Zone of Interest



Tarn Willers and Johnnie Burn






Nominees

The Creator



Ian Voigt, Erik Aadahl, Ethan Van der Ryn, Tom Ozanich and Dean Zupancic






Nominees

Maestro



Steven A. Morrow, Richard King, Jason Ruder, Tom Ozanich and Dean Zupancic






Nominees

Mission: Impossible - Dead Reckoning Part One



Chris Munro, James H. Mather, Chris Burdon and Mark Taylor






Nominees

Oppenheimer



Willie Burton, Richard King, Gary A. Rizzo and Kevin O'Connell







Visual Effects



Winner

Godzilla Minus One



Takashi Yamazaki, Kiyoko Shibuya, Masaki Takahashi and Tatsuji Nojima






Nominees

The Creator



Jay Cooper, Ian Comley, Andrew Roberts and Neil Corbould






Nominees

Guardians of the Galaxy Vol. 3



Stephane Ceretti, Alexis Wajsbrot, Guy Williams and Theo Bialek






Nominees

Mission: Impossible - Dead Reckoning Part One



Alex Wuttke, Simone Coco, Jeff Sutherland and Neil Corbould






Nominees

Napoleon



Charley Henley, Luc-Ewen Martin-Fenouillet, Simone Coco and Neil Corbould







Writing (Adapted Screenplay)



Winner

American Fiction



Written for the screen by Cord Jefferson






Nominees

Barbie



Written by Greta Gerwig & Noah Baumbach






Nominees

Oppenheimer



Written for the screen by Christopher Nolan






Nominees

Poor Things



Screenplay by Tony McNamara






Nominees

The Zone of Interest



Written by Jonathan Glazer







Writing (Original Screenplay)



Winner

Anatomy of a Fall



Screenplay - Justine Triet and Arthur Harari






Nominees

The Holdovers



Written by David Hemingson






Nominees

Maestro



Written by Bradley Cooper & Josh Singer






Nominees

May December



Screenplay by Samy Burch; Story by Samy Burch & Alex Mechanik






Nominees

Past Lives



Written by Celine Song

### Navigating the HTML tree from a specific child to find specific generic parents
Now bear with me through some additional and presently unnecessary pain. Above, we were able to isolate the 24 category groupings we wanted through finding an appropriate *parent* tag and then working *down*. But I also want to show how we could identify the same 24 category groups by finding an appropriate *child* tag and working back up. This could be helpful in other situations where the elements are hard to disambiguate.

Let's start by finding the tag for the "Actor in a Leading Role" from the soup containing all the tags.

In [ ]:
oscars_award_groups[0]

We could go up to get the parent and then find all 24 of the `<div class='view-grouping'>` among the children.

In [ ]:
# From the child we like, get its parent
oscars2018_group0_parent = oscars_parent_group[0].parent

# Now with the parent, find all the relevant children
oscars2018_group0_parent_children = oscars2018_group0_parent.find_all('div',{'class':'view-grouping'})

# Confirm
len(oscars2018_group0_parent_children)

### Checking the relevant fields

That seemed like a major digression away from the core task of writing a parser, but it is critical that we write a parser that parses *only* the data we want and nothing else. Now that we have our 24 awards groups in `oscars2018_true_groups`, let's break one open and extract all the yummy data waiting inside.

There are a few `<div>` sub-classes that are helpfully named that should make extracting this data a bit easier.

* `<div class="field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item">` - name of the category
* `<div class="field field--name-field-honoree-type winner">` - winner
* `<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">` - name of actor
* `<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">` - title of movie

In [59]:
oscars_award_groups[0]

<div class="paragraph paragraph--type--award-category paragraph--view-mode--default" data-term-id="1731">
<div class="field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item">Actor in a Leading Role</div>
<div class="field field--name-field-award-honorees field--type-entity-reference-revisions field--label-hidden field__items">
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type winner">Winner</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Cillian Murphy</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Bradley Cooper</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Maestro</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Colman Domingo</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Rustin</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Paul Giamatti</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">The Holdovers</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Jeffrey Wright</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>
</div>
</div>
</div>
</div>
</div>

"Zoom in" to the category name.

In [56]:
oscars_award_groups[-1].find_all('div',{'class':'field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item'})

"Zoom in" to the actors' names.

In [57]:
oscars_award_groups[-1].find_all('div',{'class':'field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items'})

[<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Screenplay - Justine Triet and Arthur Harari</div>
 </div>,
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Written by David Hemingson</div>
 </div>,
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Written by Bradley Cooper &amp; Josh Singer</div>
 </div>,
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Screenplay by Samy Burch; Story by Samy Burch &amp; Alex Mechanik</div>
 </div>,
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Written by Celine Song</div>
 </div>]

In [58]:
oscars_award_groups[-1].find_all('div',{'class':'field field--name-field-honoree-type winner'})

### Writing the core parser functionality

How will we map the contents of the HTML to the 

* **Year**: We'll get this from the URL
* **Category**: `'field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item'`
* **Nominee**: `'field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items'`
* **Movie**: `'field field--name-field-award-film field--type-entity-reference field--label-hidden field__item'`
* **Won**: `'field field--name-field-honoree-type winner'`

In [60]:
oscars_award_groups[0]

<div class="paragraph paragraph--type--award-category paragraph--view-mode--default" data-term-id="1731">
<div class="field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item">Actor in a Leading Role</div>
<div class="field field--name-field-award-honorees field--type-entity-reference-revisions field--label-hidden field__items">
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type winner">Winner</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Cillian Murphy</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Bradley Cooper</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Maestro</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Colman Domingo</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Rustin</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Paul Giamatti</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">The Holdovers</div>
</div>
</div>
</div>
<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Jeffrey Wright</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>
</div>
</div>
</div>
</div>
</div>

In [61]:
category = oscars_award_groups[0].find_all('div',{'class':'field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item'})[0].text
print("The name of the category is:",category)

The name of the category is: Actor in a Leading Role

In [68]:
names = []
nominees = oscars_award_groups[0].find_all('div',{'class':'field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items'})

for nominee in nominees:
    nominee_name = nominee.text
    names.append(nominee_name)
    print("The name of a nominee is:",nominee_name)

The name of a nominee is:
Cillian Murphy

The name of a nominee is:
Bradley Cooper

The name of a nominee is:
Colman Domingo

The name of a nominee is:
Paul Giamatti

The name of a nominee is:
Jeffrey Wright

In [67]:
movie_names = []
movies = oscars_award_groups[0].find_all('div',{'class':'field field--name-field-award-film field--type-entity-reference field--label-hidden field__item'})

for movie in movies:
    if len(_movie.text) > 0:
        movie_name = movie.text.strip()
        movies.append(movie_name)
        print("The name of a movie is:",movie_name)

The name of a movie is: Oppenheimer
The name of a movie is: Maestro
The name of a movie is: Rustin
The name of a movie is: The Holdovers
The name of a movie is: American Fiction

# WE MADE IT THIS FAR ON TUESDAY

Another strategy is to use the `<div class="field__item">`s for each nominee and extract the relevant information from its subdivs. This is a bit more intuitive in the sense of reading from top to bottom and also makes it easier to capture the winner and losers based on position. But again the `field__item` tags are scattered everywhere and are too non-specific to be useful or reliable.

In [76]:
len(oscars_award_groups[0].find_all('div',{'class':'field__item'}))

16

In [79]:
oscars_award_groups[0].find_all('div',{'class':'field__item'})

[<div class="field field--name-field-award-category-oscars field--type-entity-reference field--label-hidden field__item">Actor in a Leading Role</div>,
 <div class="field__item">
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type winner">Winner</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Cillian Murphy</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
 </div>
 </div>
 </div>,
 <div class="field__item">Cillian Murphy</div>,
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>,
 <div class="field__item">
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Bradley Cooper</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Maestro</div>
 </div>
 </div>
 </div>,
 <div class="field__item">Bradley Cooper</div>,
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Maestro</div>,
 <div class="field__item">
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Colman Domingo</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Rustin</div>
 </div>
 </div>
 </div>,
 <div class="field__item">Colman Domingo</div>,
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Rustin</div>,
 <div class="field__item">
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Paul Giamatti</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">The Holdovers</div>
 </div>
 </div>
 </div>,
 <div class="field__item">Paul Giamatti</div>,
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">The Holdovers</div>,
 <div class="field__item">
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Jeffrey Wright</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>
 </div>
 </div>
 </div>,
 <div class="field__item">Jeffrey Wright</div>,
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>]

The first `field__item` is the name of the category:

In [109]:
oscars_award_groups[0].find_all('div',{'class':'field__item'})[0]

The second `field__item` is the winner tag which has sub-tags that are also `field_item`s.

In [110]:
oscars_award_groups[0].find_all('div',{'class':'field__item'})[1]

<div class="field__item">
<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type winner">Winner</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Cillian Murphy</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
</div>
</div>
</div>

The last `field__item` should be Jeffrey Wright, but it's a sub `field__item` about the movie that exists withing the larger string "field field--name-field-award-film field--type-entity-reference field--label-hidden **field__item**".

In [111]:
oscars_award_groups[0].find_all('div',{'class':'field__item'})[-1]

This is a good lesson that BeautifulSoup's `find_all` function picks up *any* of the text fields in the "class" value. Let's test whether we can just search for a value like `paragraph--type--award-honoree` instead of the whole gigantic string.

In [78]:
oscars_award_groups[0].find_all('div',{'class':'paragraph--type--award-honoree'})

[<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type winner">Winner</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Cillian Murphy</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
 </div>
 </div>,
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Bradley Cooper</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Maestro</div>
 </div>
 </div>,
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Colman Domingo</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Rustin</div>
 </div>
 </div>,
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Paul Giamatti</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">The Holdovers</div>
 </div>
 </div>,
 <div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
 <div class="field field--name-field-honoree-type nominee">Nominees</div>
 <div class="field">
 <div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
 <div class="field__item">Jeffrey Wright</div>
 </div>
 </div>
 <div class="field">
 <div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>
 </div>
 </div>]

Does the first one have all the information about the first nominee? Winner, Movie, Name?

In [80]:
oscars_award_groups[0].find_all('div',{'class':'paragraph--type--award-honoree'})[0]

<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type winner">Winner</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Cillian Murphy</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">Oppenheimer</div>
</div>
</div>

Does the last one have all the information: winner, movie, name?

In [112]:
oscars_award_groups[0].find_all('div',{'class':'paragraph--type--award-honoree'})[-1]

<div class="paragraph paragraph--type--award-honoree paragraph--view-mode--oscars">
<div class="field field--name-field-honoree-type nominee">Nominees</div>
<div class="field">
<div class="field field--name-field-award-entities field--type-entity-reference field--label-hidden field__items">
<div class="field__item">Jeffrey Wright</div>
</div>
</div>
<div class="field">
<div class="field field--name-field-award-film field--type-entity-reference field--label-hidden field__item">American Fiction</div>
</div>
</div>

In [115]:
nominees = oscars_award_groups[0].find_all('div',{'class':'paragraph--type--award-honoree'})

Use the `.find` method on each nominee's tag to pull out the relevant information:

* Winner: `field--name-field-honoree-type`
* Name: `field--name-field-award-entities`
* Film: `field--name-field-award-film`

Use the `.strip()` method to clear out any wacky characters or newlines hiding at the beginning or end of the string.

In [116]:
nominees[0].find('div',{'class':'field--name-field-honoree-type'}).text.strip()

'Winner'

In [117]:
nominees[0].find('div',{'class':'field--name-field-award-entities'}).text.strip()

'Cillian Murphy'

In [118]:
nominees[0].find('div',{'class':'field--name-field-award-film'}).text.strip()

'Oppenheimer'

Put it all together for all the nominees.

In [119]:
nominees = oscars_award_groups[0].find_all('div',{'class':'paragraph--type--award-honoree'})

# Loop through each nominee
for nominee in nominees:
    
    # Get the honoree type
    nom_winner = nominee.find('div',{'class':'field--name-field-honoree-type'}).text.strip()
    
    # Get the name
    nom_name = nominee.find('div',{'class':'field--name-field-award-entities'}).text.strip()
    
    # Get the movie
    nom_movie = nominee.find('div',{'class':'field--name-field-award-film'}).text.strip()
    
    print("{0} was nominated for \"{1}\" and was a {2}.".format(nom_name,nom_movie,nom_winner))

Cillian Murphy was nominated for "Oppenheimer" and was a Winner.
Bradley Cooper was nominated for "Maestro" and was a Nominees.
Colman Domingo was nominated for "Rustin" and was a Nominees.
Paul Giamatti was nominated for "The Holdovers" and was a Nominees.
Jeffrey Wright was nominated for "American Fiction" and was a Nominees.

Check that reversing "movie" and "name" works for another award category like original screenplay (`oscars_award_groups[-1]`). There's some weirdness with "Written by" and "Story by" filtering in here rather than simply names that may need to get fixed in the final calculation, but I would want to talk to a domain expert about the differences between these labels.

In [120]:
nominees = oscars_award_groups[-1].find_all('div',{'class':'paragraph--type--award-honoree'})

# Loop through each nominee
for nominee in nominees:
    
    # Get the honoree type
    nom_winner = nominee.find('div',{'class':'field--name-field-honoree-type'}).text.strip()
    
    # Get the name
    nom_name = nominee.find('div',{'class':'field--name-field-award-entities'}).text.strip()
    
    # Get the movie
    nom_movie = nominee.find('div',{'class':'field--name-field-award-film'}).text.strip()
    
    print("{0} was nominated for \"{1}\" and was a {2}.".format(nom_name,nom_movie,nom_winner))

Screenplay - Justine Triet and Arthur Harari was nominated for "Anatomy of a Fall" and was a Winner.
Written by David Hemingson was nominated for "The Holdovers" and was a Nominees.
Written by Bradley Cooper & Josh Singer was nominated for "Maestro" and was a Nominees.
Screenplay by Samy Burch; Story by Samy Burch & Alex Mechanik was nominated for "May December" and was a Nominees.
Written by Celine Song was nominated for "Past Lives" and was a Nominees.

This was just for Best Actors, now lets add another layer for all the different awards categories. We can see the movie name and awardee switch is important now since most of the categories are reversed.

The nominee category is saved in: `field--name-field-honoree-type`

In [104]:
oscars_award_groups[0].find('div',{'class':'field--name-field-award-category-oscars'}).text.strip()

'Actor in a Leading Role'

Let's build on our previous loop and add an outer layer to loop through all the nominees.

In [121]:
# For each award group
for group in oscars_award_groups:

    # Get the name of the category
    category = group.find('div',{'class':'field--name-field-award-category-oscars'}).text.strip()

    # Get all the nominees in the group
    nominees = group.find_all('div',{'class':'paragraph--type--award-honoree'})
    
    # Loop through each nominee
    for nominee in nominees:
        
        # Get the honoree type
        nom_winner = nominee.find('div',{'class':'field--name-field-honoree-type'}).text.strip()
        
        # Get the name
        nom_name = nominee.find('div',{'class':'field--name-field-award-entities'}).text.strip()
        
        # Get the movie
        nom_movie = nominee.find('div',{'class':'field--name-field-award-film'}).text.strip()

        # Print it out
        print("{0} was nominated in {1} for \"{2}\" and was a {3}.".format(nom_name,category,nom_movie,nom_winner))

    print("\n")

Cillian Murphy was nominated in Actor in a Leading Role for "Oppenheimer" and was a Winner.
Bradley Cooper was nominated in Actor in a Leading Role for "Maestro" and was a Nominees.
Colman Domingo was nominated in Actor in a Leading Role for "Rustin" and was a Nominees.
Paul Giamatti was nominated in Actor in a Leading Role for "The Holdovers" and was a Nominees.
Jeffrey Wright was nominated in Actor in a Leading Role for "American Fiction" and was a Nominees.


Robert Downey Jr. was nominated in Actor in a Supporting Role for "Oppenheimer" and was a Winner.
Sterling K. Brown was nominated in Actor in a Supporting Role for "American Fiction" and was a Nominees.
Robert De Niro was nominated in Actor in a Supporting Role for "Killers of the Flower Moon" and was a Nominees.
Ryan Gosling was nominated in Actor in a Supporting Role for "Barbie" and was a Nominees.
Mark Ruffalo was nominated in Actor in a Supporting Role for "Poor Things" and was a Nominees.


Emma Stone was nominated in Actress in a Leading Role for "Poor Things" and was a Winner.
Annette Bening was nominated in Actress in a Leading Role for "Nyad" and was a Nominees.
Lily Gladstone was nominated in Actress in a Leading Role for "Killers of the Flower Moon" and was a Nominees.
Sandra Hüller was nominated in Actress in a Leading Role for "Anatomy of a Fall" and was a Nominees.
Carey Mulligan was nominated in Actress in a Leading Role for "Maestro" and was a Nominees.


Da'Vine Joy Randolph was nominated in Actress in a Supporting Role for "The Holdovers" and was a Winner.
Emily Blunt was nominated in Actress in a Supporting Role for "Oppenheimer" and was a Nominees.
Danielle Brooks was nominated in Actress in a Supporting Role for "The Color Purple" and was a Nominees.
America Ferrera was nominated in Actress in a Supporting Role for "Barbie" and was a Nominees.
Jodie Foster was nominated in Actress in a Supporting Role for "Nyad" and was a Nominees.


Hayao Miyazaki and Toshio Suzuki was nominated in Animated Feature Film for "The Boy and the Heron" and was a Winner.
Peter Sohn and Denise Ream was nominated in Animated Feature Film for "Elemental" and was a Nominees.
Nick Bruno, Troy Quane, Karen Ryan and Julie Zackary was nominated in Animated Feature Film for "Nimona" and was a Nominees.
Pablo Berger, Ibon Cormenzana, Ignasi Estapé and Sandra Tapia Díaz was nominated in Animated Feature Film for "Robot Dreams" and was a Nominees.
Kemp Powers, Justin K. Thompson, Phil Lord, Christopher Miller and Amy Pascal was nominated in Animated Feature Film for "Spider-Man: Across the Spider-Verse" and was a Nominees.


Hoyte van Hoytema was nominated in Cinematography for "Oppenheimer" and was a Winner.
Edward Lachman was nominated in Cinematography for "El Conde" and was a Nominees.
Rodrigo Prieto was nominated in Cinematography for "Killers of the Flower Moon" and was a Nominees.
Matthew Libatique was nominated in Cinematography for "Maestro" and was a Nominees.
Robbie Ryan was nominated in Cinematography for "Poor Things" and was a Nominees.


Holly Waddington was nominated in Costume Design for "Poor Things" and was a Winner.
Jacqueline Durran was nominated in Costume Design for "Barbie" and was a Nominees.
Jacqueline West was nominated in Costume Design for "Killers of the Flower Moon" and was a Nominees.
Janty Yates and Dave Crossman was nominated in Costume Design for "Napoleon" and was a Nominees.
Ellen Mirojnick was nominated in Costume Design for "Oppenheimer" and was a Nominees.


Christopher Nolan was nominated in Directing for "Oppenheimer" and was a Winner.
Justine Triet was nominated in Directing for "Anatomy of a Fall" and was a Nominees.
Martin Scorsese was nominated in Directing for "Killers of the Flower Moon" and was a Nominees.
Yorgos Lanthimos was nominated in Directing for "Poor Things" and was a Nominees.
Jonathan Glazer was nominated in Directing for "The Zone of Interest" and was a Nominees.


Mstyslav Chernov, Michelle Mizner and Raney Aronson-Rath was nominated in Documentary Feature Film for "20 Days in Mariupol" and was a Winner.
Moses Bwayo, Christopher Sharp and John Battsek was nominated in Documentary Feature Film for "Bobi Wine: The People's President" and was a Nominees.
Maite Alberdi was nominated in Documentary Feature Film for "The Eternal Memory" and was a Nominees.
Kaouther Ben Hania and Nadim Cheikhrouha was nominated in Documentary Feature Film for "Four Daughters" and was a Nominees.
Nisha Pahuja, Cornelia Principe and David Oppenheim was nominated in Documentary Feature Film for "To Kill a Tiger" and was a Nominees.


Ben Proudfoot and Kris Bowers was nominated in Documentary Short Film for "The Last Repair Shop" and was a Winner.
Sheila Nevins and Trish Adlesic was nominated in Documentary Short Film for "The ABCs of Book Banning" and was a Nominees.
John Hoffman and Christine Turner was nominated in Documentary Short Film for "The Barber of Little Rock" and was a Nominees.
S. Leo Chiang and Jean Tsien was nominated in Documentary Short Film for "Island in Between" and was a Nominees.
Sean Wang and Sam Davis was nominated in Documentary Short Film for "Nǎi Nai & Wài Pó" and was a Nominees.


Jennifer Lame was nominated in Film Editing for "Oppenheimer" and was a Winner.
Laurent Sénéchal was nominated in Film Editing for "Anatomy of a Fall" and was a Nominees.
Kevin Tent was nominated in Film Editing for "The Holdovers" and was a Nominees.
Thelma Schoonmaker was nominated in Film Editing for "Killers of the Flower Moon" and was a Nominees.
Yorgos Mavropsaridis was nominated in Film Editing for "Poor Things" and was a Nominees.


The Zone of Interest was nominated in International Feature Film for "United Kingdom" and was a Winner.
Io Capitano was nominated in International Feature Film for "Italy" and was a Nominees.
Perfect Days was nominated in International Feature Film for "Japan" and was a Nominees.
Society of the Snow was nominated in International Feature Film for "Spain" and was a Nominees.
The Teachers' Lounge was nominated in International Feature Film for "Germany" and was a Nominees.


Nadia Stacey, Mark Coulier and Josh Weston was nominated in Makeup and Hairstyling for "Poor Things" and was a Winner.
Karen Hartley Thomas, Suzi Battersby and Ashra Kelly-Blue was nominated in Makeup and Hairstyling for "Golda" and was a Nominees.
Kazu Hiro, Kay Georgiou and Lori McCoy-Bell was nominated in Makeup and Hairstyling for "Maestro" and was a Nominees.
Luisa Abel was nominated in Makeup and Hairstyling for "Oppenheimer" and was a Nominees.
Ana López-Puigcerver, David Martí and Montse Ribé was nominated in Makeup and Hairstyling for "Society of the Snow" and was a Nominees.


Ludwig Göransson was nominated in Music (Original Score) for "Oppenheimer" and was a Winner.
Laura Karpman was nominated in Music (Original Score) for "American Fiction" and was a Nominees.
John Williams was nominated in Music (Original Score) for "Indiana Jones and the Dial of Destiny" and was a Nominees.
Robbie Robertson was nominated in Music (Original Score) for "Killers of the Flower Moon" and was a Nominees.
Jerskin Fendrix was nominated in Music (Original Score) for "Poor Things" and was a Nominees.


from Barbie; Music and Lyric by Billie Eilish and Finneas O'Connell was nominated in Music (Original Song) for "What Was I Made For?" and was a Winner.
from Flamin' Hot; Music and Lyric by Diane Warren was nominated in Music (Original Song) for "The Fire Inside" and was a Nominees.
from Barbie; Music and Lyric by Mark Ronson and Andrew Wyatt was nominated in Music (Original Song) for "I'm Just Ken" and was a Nominees.
from American Symphony; Music and Lyric by Jon Batiste and Dan Wilson was nominated in Music (Original Song) for "It Never Went Away" and was a Nominees.
from Killers of the Flower Moon; Music and Lyric by Scott George was nominated in Music (Original Song) for "Wahzhazhe (A Song For My People)" and was a Nominees.


Emma Thomas, Charles Roven and Christopher Nolan, Producers was nominated in Best Picture for "Oppenheimer" and was a Winner.
Ben LeClair, Nikos Karamigios, Cord Jefferson and Jermaine Johnson, Producers was nominated in Best Picture for "American Fiction" and was a Nominees.
Marie-Ange Luciani and David Thion, Producers was nominated in Best Picture for "Anatomy of a Fall" and was a Nominees.
David Heyman, Margot Robbie, Tom Ackerley and Robbie Brenner, Producers was nominated in Best Picture for "Barbie" and was a Nominees.
Mark Johnson, Producer was nominated in Best Picture for "The Holdovers" and was a Nominees.
Dan Friedkin, Bradley Thomas, Martin Scorsese and Daniel Lupi, Producers was nominated in Best Picture for "Killers of the Flower Moon" and was a Nominees.
Bradley Cooper, Steven Spielberg, Fred Berner, Amy Durning and Kristie Macosko Krieger, Producers was nominated in Best Picture for "Maestro" and was a Nominees.
David Hinojosa, Christine Vachon and Pamela Koffler, Producers was nominated in Best Picture for "Past Lives" and was a Nominees.
Ed Guiney, Andrew Lowe, Yorgos Lanthimos and Emma Stone, Producers was nominated in Best Picture for "Poor Things" and was a Nominees.
James Wilson, Producer was nominated in Best Picture for "The Zone of Interest" and was a Nominees.


Production Design: James Price and Shona Heath; Set Decoration: Zsuzsa Mihalek was nominated in Production Design for "Poor Things" and was a Winner.
Production Design: Sarah Greenwood; Set Decoration: Katie Spencer was nominated in Production Design for "Barbie" and was a Nominees.
Production Design: Jack Fisk; Set Decoration: Adam Willis was nominated in Production Design for "Killers of the Flower Moon" and was a Nominees.
Production Design: Arthur Max; Set Decoration: Elli Griff was nominated in Production Design for "Napoleon" and was a Nominees.
Production Design: Ruth De Jong; Set Decoration: Claire Kaufman was nominated in Production Design for "Oppenheimer" and was a Nominees.


Dave Mullins and Brad Booker was nominated in Animated Short Film for "WAR IS OVER! Inspired by the Music of John & Yoko" and was a Winner.
Tal Kantor and Amit R. Gicelter was nominated in Animated Short Film for "Letter to a Pig" and was a Nominees.
Jerusha Hess and Jared Hess was nominated in Animated Short Film for "Ninety-Five Senses" and was a Nominees.
Yegane Moghaddam was nominated in Animated Short Film for "Our Uniform" and was a Nominees.
Stéphanie Clément and Marc Rius was nominated in Animated Short Film for "Pachyderme" and was a Nominees.


Wes Anderson and Steven Rales was nominated in Live Action Short Film for "The Wonderful Story of Henry Sugar" and was a Winner.
Misan Harriman and Nicky Bentham was nominated in Live Action Short Film for "The After" and was a Nominees.
Vincent René-Lortie and Samuel Caron was nominated in Live Action Short Film for "Invincible" and was a Nominees.
Lasse Lyskjær Noer and Christian Norlyk was nominated in Live Action Short Film for "Knight of Fortune" and was a Nominees.
Nazrin Choudhury and Sara McFarlane was nominated in Live Action Short Film for "Red, White and Blue" and was a Nominees.


Tarn Willers and Johnnie Burn was nominated in Sound for "The Zone of Interest" and was a Winner.
Ian Voigt, Erik Aadahl, Ethan Van der Ryn, Tom Ozanich and Dean Zupancic was nominated in Sound for "The Creator" and was a Nominees.
Steven A. Morrow, Richard King, Jason Ruder, Tom Ozanich and Dean Zupancic was nominated in Sound for "Maestro" and was a Nominees.
Chris Munro, James H. Mather, Chris Burdon and Mark Taylor was nominated in Sound for "Mission: Impossible - Dead Reckoning Part One" and was a Nominees.
Willie Burton, Richard King, Gary A. Rizzo and Kevin O'Connell was nominated in Sound for "Oppenheimer" and was a Nominees.


Takashi Yamazaki, Kiyoko Shibuya, Masaki Takahashi and Tatsuji Nojima was nominated in Visual Effects for "Godzilla Minus One" and was a Winner.
Jay Cooper, Ian Comley, Andrew Roberts and Neil Corbould was nominated in Visual Effects for "The Creator" and was a Nominees.
Stephane Ceretti, Alexis Wajsbrot, Guy Williams and Theo Bialek was nominated in Visual Effects for "Guardians of the Galaxy Vol. 3" and was a Nominees.
Alex Wuttke, Simone Coco, Jeff Sutherland and Neil Corbould was nominated in Visual Effects for "Mission: Impossible - Dead Reckoning Part One" and was a Nominees.
Charley Henley, Luc-Ewen Martin-Fenouillet, Simone Coco and Neil Corbould was nominated in Visual Effects for "Napoleon" and was a Nominees.


Written for the screen by Cord Jefferson was nominated in Writing (Adapted Screenplay) for "American Fiction" and was a Winner.
Written by Greta Gerwig & Noah Baumbach was nominated in Writing (Adapted Screenplay) for "Barbie" and was a Nominees.
Written for the screen by Christopher Nolan was nominated in Writing (Adapted Screenplay) for "Oppenheimer" and was a Nominees.
Screenplay by Tony McNamara was nominated in Writing (Adapted Screenplay) for "Poor Things" and was a Nominees.
Written by Jonathan Glazer was nominated in Writing (Adapted Screenplay) for "The Zone of Interest" and was a Nominees.


Screenplay - Justine Triet and Arthur Harari was nominated in Writing (Original Screenplay) for "Anatomy of a Fall" and was a Winner.
Written by David Hemingson was nominated in Writing (Original Screenplay) for "The Holdovers" and was a Nominees.
Written by Bradley Cooper & Josh Singer was nominated in Writing (Original Screenplay) for "Maestro" and was a Nominees.
Screenplay by Samy Burch; Story by Samy Burch & Alex Mechanik was nominated in Writing (Original Screenplay) for "May December" and was a Nominees.
Written by Celine Song was nominated in Writing (Original Screenplay) for "Past Lives" and was a Nominees.

Rather than printing out the information, store it in `nominees_2018` so that we can turn it into a DataFrame.

In [123]:
nominees_l = []

# For each award group
for group in oscars_award_groups:

    # Get the name of the category
    category = group.find('div',{'class':'field--name-field-award-category-oscars'}).text.strip()

    # Get all the nominees in the group
    nominees = group.find_all('div',{'class':'paragraph--type--award-honoree'})
    
    # Loop through each nominee
    for nominee in nominees:
        
        # Get the honoree type
        nom_winner = nominee.find('div',{'class':'field--name-field-honoree-type'}).text.strip()
        
        # Get the name
        nom_name = nominee.find('div',{'class':'field--name-field-award-entities'}).text.strip()
        
        # Get the movie
        nom_movie = nominee.find('div',{'class':'field--name-field-award-film'}).text.strip()

        # Make a payload for each nominee
        nominee_payload = {
            'Category':category,
            'Name':nom_name,
            'Movie':nom_movie,
            'Year':2024, # We're only looking at 2018 right now
            'Winner':nom_winner
        }
        
        # Add the payload to the list of nominees at top
        nominees_l.append(nominee_payload)

Moment of truth!

In [124]:
nominees_df = pd.DataFrame(nominees_l)
nominees_df

,Category,Name,Movie,Year,Winner
0,Actor in a Leading Role,Cillian Murphy,Oppenheimer,2024,Winner
1,Actor in a Leading Role,Bradley Cooper,Maestro,2024,Nominees
2,Actor in a Leading Role,Colman Domingo,Rustin,2024,Nominees
3,Actor in a Leading Role,Paul Giamatti,The Holdovers,2024,Nominees
4,Actor in a Leading Role,Jeffrey Wright,American Fiction,2024,Nominees
...,...,...,...,...,...
115,Writing (Original Screenplay),Screenplay - Justine Triet and Arthur Harari,Anatomy of a Fall,2024,Winner
116,Writing (Original Screenplay),Written by David Hemingson,The Holdovers,2024,Nominees
117,Writing (Original Screenplay),Written by Bradley Cooper & Josh Singer,Maestro,2024,Nominees
118,Writing (Original Screenplay),Screenplay by Samy Burch; Story by Samy Burch ...,May December,2024,Nominees
119,Writing (Original Screenplay),Written by Celine Song,Past Lives,2024,Nominees

In [126]:
nominees_df['Movie'].value_counts()

Movie
Oppenheimer                                          13
Poor Things                                          11
Killers of the Flower Moon                            9
Maestro                                               7
Barbie                                                6
Anatomy of a Fall                                     5
The Holdovers                                         5
American Fiction                                      5
The Zone of Interest                                  4
Napoleon                                              3
The Creator                                           2
Nyad                                                  2
Past Lives                                            2
Mission: Impossible - Dead Reckoning Part One         2
Godzilla Minus One                                    1
WAR IS OVER! Inspired by the Music of John & Yoko     1
Indiana Jones and the Dial of Destiny                 1
What Was I Made For?                                  1
The Fire Inside                                       1
Guardians of the Galaxy Vol. 3                        1
I'm Just Ken                                          1
It Never Went Away                                    1
Wahzhazhe (A Song For My People)                      1
Ninety-Five Senses                                    1
Letter to a Pig                                       1
Our Uniform                                           1
Pachyderme                                            1
The Wonderful Story of Henry Sugar                    1
Golda                                                 1
The After                                             1
Invincible                                            1
Knight of Fortune                                     1
Red, White and Blue                                   1
Society of the Snow                                   1
United Kingdom                                        1
Germany                                               1
Bobi Wine: The People's President                     1
Rustin                                                1
The Color Purple                                      1
The Boy and the Heron                                 1
Elemental                                             1
Nimona                                                1
Robot Dreams                                          1
Spider-Man: Across the Spider-Verse                   1
El Conde                                              1
20 Days in Mariupol                                   1
The Eternal Memory                                    1
Spain                                                 1
Four Daughters                                        1
To Kill a Tiger                                       1
The Last Repair Shop                                  1
The ABCs of Book Banning                              1
The Barber of Little Rock                             1
Island in Between                                     1
Nǎi Nai & Wài Pó                                      1
Italy                                                 1
Japan                                                 1
May December                                          1
Name: count, dtype: int64

Now let's turn this hulking beast of a parser into a function so we can apply it to other years' nominees in the next step.

In [174]:
def parse_nominees(oscars_award_groups,year):
    nominees_l = []

    # For each award group
    for group in oscars_award_groups:
    
        # Get the name of the category
        category = group.find('div',{'class':'field--name-field-award-category-oscars'}).text.strip()
    
        # Get all the nominees in the group
        nominees = group.find_all('div',{'class':'paragraph--type--award-honoree'})
        
        # Loop through each nominee
        for nominee in nominees:
            
            # Get the honoree type
            try:
                nom_winner = nominee.find('div',{'class':'field--name-field-honoree-type'}).text.strip()
            except:
                nom_winner = ''
            
            # Get the name
            try:
                nom_name = nominee.find('div',{'class':'field--name-field-award-entities'}).text.strip()
            except:
                nom_name = ''
            
            # Get the movie
            try:
                nom_movie = nominee.find('div',{'class':'field--name-field-award-film'}).text.strip()
            except:
                nom_movie = ''
    
            # Make a payload for each nominee
            nominee_payload = {
                'Category':category,
                'Name':nom_name,
                'Movie':nom_movie,
                'Year':year,
                'Winner':nom_winner
            }
            
            # Add the payload to the list of nominees at top
            nominees_l.append(nominee_payload)
    
    return nominees_l

In [130]:
parse_nominees(oscars_award_groups,2024)

[{'Category': 'Actor in a Leading Role',
  'Name': 'Cillian Murphy',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Actor in a Leading Role',
  'Name': 'Bradley Cooper',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Leading Role',
  'Name': 'Colman Domingo',
  'Movie': 'Rustin',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Leading Role',
  'Name': 'Paul Giamatti',
  'Movie': 'The Holdovers',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Leading Role',
  'Name': 'Jeffrey Wright',
  'Movie': 'American Fiction',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Supporting Role',
  'Name': 'Robert Downey Jr.',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Actor in a Supporting Role',
  'Name': 'Sterling K. Brown',
  'Movie': 'American Fiction',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Supporting Role',
  'Name': 'Robert De Niro',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Supporting Role',
  'Name': 'Ryan Gosling',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actor in a Supporting Role',
  'Name': 'Mark Ruffalo',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Leading Role',
  'Name': 'Emma Stone',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Actress in a Leading Role',
  'Name': 'Annette Bening',
  'Movie': 'Nyad',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Leading Role',
  'Name': 'Lily Gladstone',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Leading Role',
  'Name': 'Sandra Hüller',
  'Movie': 'Anatomy of a Fall',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Leading Role',
  'Name': 'Carey Mulligan',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Supporting Role',
  'Name': "Da'Vine Joy Randolph",
  'Movie': 'The Holdovers',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Actress in a Supporting Role',
  'Name': 'Emily Blunt',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Supporting Role',
  'Name': 'Danielle Brooks',
  'Movie': 'The Color Purple',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Supporting Role',
  'Name': 'America Ferrera',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Actress in a Supporting Role',
  'Name': 'Jodie Foster',
  'Movie': 'Nyad',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Feature Film',
  'Name': 'Hayao Miyazaki and Toshio Suzuki',
  'Movie': 'The Boy and the Heron',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Animated Feature Film',
  'Name': 'Peter Sohn and Denise Ream',
  'Movie': 'Elemental',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Feature Film',
  'Name': 'Nick Bruno, Troy Quane, Karen Ryan and Julie Zackary',
  'Movie': 'Nimona',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Feature Film',
  'Name': 'Pablo Berger, Ibon Cormenzana, Ignasi Estapé and Sandra Tapia Díaz',
  'Movie': 'Robot Dreams',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Feature Film',
  'Name': 'Kemp Powers, Justin K. Thompson, Phil Lord, Christopher Miller and Amy Pascal',
  'Movie': 'Spider-Man: Across the Spider-Verse',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Cinematography',
  'Name': 'Hoyte van Hoytema',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Cinematography',
  'Name': 'Edward Lachman',
  'Movie': 'El Conde',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Cinematography',
  'Name': 'Rodrigo Prieto',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Cinematography',
  'Name': 'Matthew Libatique',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Cinematography',
  'Name': 'Robbie Ryan',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Costume Design',
  'Name': 'Holly Waddington',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Costume Design',
  'Name': 'Jacqueline Durran',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Costume Design',
  'Name': 'Jacqueline West',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Costume Design',
  'Name': 'Janty Yates and Dave Crossman',
  'Movie': 'Napoleon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Costume Design',
  'Name': 'Ellen Mirojnick',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Directing',
  'Name': 'Christopher Nolan',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Directing',
  'Name': 'Justine Triet',
  'Movie': 'Anatomy of a Fall',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Directing',
  'Name': 'Martin Scorsese',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Directing',
  'Name': 'Yorgos Lanthimos',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Directing',
  'Name': 'Jonathan Glazer',
  'Movie': 'The Zone of Interest',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Feature Film',
  'Name': 'Mstyslav Chernov, Michelle Mizner and Raney Aronson-Rath',
  'Movie': '20 Days in Mariupol',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Documentary Feature Film',
  'Name': 'Moses Bwayo, Christopher Sharp and John Battsek',
  'Movie': "Bobi Wine: The People's President",
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Feature Film',
  'Name': 'Maite Alberdi',
  'Movie': 'The Eternal Memory',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Feature Film',
  'Name': 'Kaouther Ben Hania and Nadim Cheikhrouha',
  'Movie': 'Four Daughters',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Feature Film',
  'Name': 'Nisha Pahuja, Cornelia Principe and David Oppenheim',
  'Movie': 'To Kill a Tiger',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Short Film',
  'Name': 'Ben Proudfoot and Kris Bowers',
  'Movie': 'The Last Repair Shop',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Documentary Short Film',
  'Name': 'Sheila Nevins and Trish Adlesic',
  'Movie': 'The ABCs of Book Banning',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Short Film',
  'Name': 'John Hoffman and Christine Turner',
  'Movie': 'The Barber of Little Rock',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Short Film',
  'Name': 'S. Leo Chiang and Jean Tsien',
  'Movie': 'Island in Between',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Documentary Short Film',
  'Name': 'Sean Wang and Sam Davis',
  'Movie': 'Nǎi Nai & Wài Pó',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Film Editing',
  'Name': 'Jennifer Lame',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Film Editing',
  'Name': 'Laurent Sénéchal',
  'Movie': 'Anatomy of a Fall',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Film Editing',
  'Name': 'Kevin Tent',
  'Movie': 'The Holdovers',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Film Editing',
  'Name': 'Thelma Schoonmaker',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Film Editing',
  'Name': 'Yorgos Mavropsaridis',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'International Feature Film',
  'Name': 'The Zone of Interest',
  'Movie': 'United Kingdom',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'International Feature Film',
  'Name': 'Io Capitano',
  'Movie': 'Italy',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'International Feature Film',
  'Name': 'Perfect Days',
  'Movie': 'Japan',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'International Feature Film',
  'Name': 'Society of the Snow',
  'Movie': 'Spain',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'International Feature Film',
  'Name': "The Teachers' Lounge",
  'Movie': 'Germany',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Makeup and Hairstyling',
  'Name': 'Nadia Stacey, Mark Coulier and Josh Weston',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Makeup and Hairstyling',
  'Name': 'Karen Hartley Thomas, Suzi Battersby and Ashra Kelly-Blue',
  'Movie': 'Golda',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Makeup and Hairstyling',
  'Name': 'Kazu Hiro, Kay Georgiou and Lori McCoy-Bell',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Makeup and Hairstyling',
  'Name': 'Luisa Abel',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Makeup and Hairstyling',
  'Name': 'Ana López-Puigcerver, David Martí and Montse Ribé',
  'Movie': 'Society of the Snow',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Score)',
  'Name': 'Ludwig Göransson',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Music (Original Score)',
  'Name': 'Laura Karpman',
  'Movie': 'American Fiction',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Score)',
  'Name': 'John Williams',
  'Movie': 'Indiana Jones and the Dial of Destiny',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Score)',
  'Name': 'Robbie Robertson',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Score)',
  'Name': 'Jerskin Fendrix',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Song)',
  'Name': "from Barbie; Music and Lyric by Billie Eilish and Finneas O'Connell",
  'Movie': 'What Was I Made For?',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Music (Original Song)',
  'Name': "from Flamin' Hot; Music and Lyric by Diane Warren",
  'Movie': 'The Fire Inside',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Song)',
  'Name': 'from Barbie; Music and Lyric by Mark Ronson and Andrew Wyatt',
  'Movie': "I'm Just Ken",
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Song)',
  'Name': 'from American Symphony; Music and Lyric by Jon Batiste and Dan Wilson',
  'Movie': 'It Never Went Away',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Music (Original Song)',
  'Name': 'from Killers of the Flower Moon; Music and Lyric by Scott George',
  'Movie': 'Wahzhazhe (A Song For My People)',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Emma Thomas, Charles Roven and Christopher Nolan, Producers',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Best Picture',
  'Name': 'Ben LeClair, Nikos Karamigios, Cord Jefferson and Jermaine Johnson, Producers',
  'Movie': 'American Fiction',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Marie-Ange Luciani and David Thion, Producers',
  'Movie': 'Anatomy of a Fall',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'David Heyman, Margot Robbie, Tom Ackerley and Robbie Brenner, Producers',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Mark Johnson, Producer',
  'Movie': 'The Holdovers',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Dan Friedkin, Bradley Thomas, Martin Scorsese and Daniel Lupi, Producers',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Bradley Cooper, Steven Spielberg, Fred Berner, Amy Durning and Kristie Macosko Krieger, Producers',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'David Hinojosa, Christine Vachon and Pamela Koffler, Producers',
  'Movie': 'Past Lives',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'Ed Guiney, Andrew Lowe, Yorgos Lanthimos and Emma Stone, Producers',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Best Picture',
  'Name': 'James Wilson, Producer',
  'Movie': 'The Zone of Interest',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Production Design',
  'Name': 'Production Design: James Price and Shona Heath; Set Decoration: Zsuzsa Mihalek',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Production Design',
  'Name': 'Production Design: Sarah Greenwood; Set Decoration: Katie Spencer',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Production Design',
  'Name': 'Production Design: Jack Fisk; Set Decoration: Adam Willis',
  'Movie': 'Killers of the Flower Moon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Production Design',
  'Name': 'Production Design: Arthur Max; Set Decoration: Elli Griff',
  'Movie': 'Napoleon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Production Design',
  'Name': 'Production Design: Ruth De Jong; Set Decoration: Claire Kaufman',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Short Film',
  'Name': 'Dave Mullins and Brad Booker',
  'Movie': 'WAR IS OVER! Inspired by the Music of John & Yoko',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Animated Short Film',
  'Name': 'Tal Kantor and Amit R. Gicelter',
  'Movie': 'Letter to a Pig',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Short Film',
  'Name': 'Jerusha Hess and Jared Hess',
  'Movie': 'Ninety-Five Senses',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Short Film',
  'Name': 'Yegane Moghaddam',
  'Movie': 'Our Uniform',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Animated Short Film',
  'Name': 'Stéphanie Clément and Marc Rius',
  'Movie': 'Pachyderme',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Live Action Short Film',
  'Name': 'Wes Anderson and Steven Rales',
  'Movie': 'The Wonderful Story of Henry Sugar',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Live Action Short Film',
  'Name': 'Misan Harriman and Nicky Bentham',
  'Movie': 'The After',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Live Action Short Film',
  'Name': 'Vincent René-Lortie and Samuel Caron',
  'Movie': 'Invincible',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Live Action Short Film',
  'Name': 'Lasse Lyskjær Noer and Christian Norlyk',
  'Movie': 'Knight of Fortune',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Live Action Short Film',
  'Name': 'Nazrin Choudhury and Sara McFarlane',
  'Movie': 'Red, White and Blue',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Sound',
  'Name': 'Tarn Willers and Johnnie Burn',
  'Movie': 'The Zone of Interest',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Sound',
  'Name': 'Ian Voigt, Erik Aadahl, Ethan Van der Ryn, Tom Ozanich and Dean Zupancic',
  'Movie': 'The Creator',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Sound',
  'Name': 'Steven A. Morrow, Richard King, Jason Ruder, Tom Ozanich and Dean Zupancic',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Sound',
  'Name': 'Chris Munro, James H. Mather, Chris Burdon and Mark Taylor',
  'Movie': 'Mission: Impossible - Dead Reckoning Part One',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Sound',
  'Name': "Willie Burton, Richard King, Gary A. Rizzo and Kevin O'Connell",
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Visual Effects',
  'Name': 'Takashi Yamazaki, Kiyoko Shibuya, Masaki Takahashi and Tatsuji Nojima',
  'Movie': 'Godzilla Minus One',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Visual Effects',
  'Name': 'Jay Cooper, Ian Comley, Andrew Roberts and Neil Corbould',
  'Movie': 'The Creator',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Visual Effects',
  'Name': 'Stephane Ceretti, Alexis Wajsbrot, Guy Williams and Theo Bialek',
  'Movie': 'Guardians of the Galaxy Vol. 3',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Visual Effects',
  'Name': 'Alex Wuttke, Simone Coco, Jeff Sutherland and Neil Corbould',
  'Movie': 'Mission: Impossible - Dead Reckoning Part One',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Visual Effects',
  'Name': 'Charley Henley, Luc-Ewen Martin-Fenouillet, Simone Coco and Neil Corbould',
  'Movie': 'Napoleon',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Adapted Screenplay)',
  'Name': 'Written for the screen by Cord Jefferson',
  'Movie': 'American Fiction',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Writing (Adapted Screenplay)',
  'Name': 'Written by Greta Gerwig & Noah Baumbach',
  'Movie': 'Barbie',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Adapted Screenplay)',
  'Name': 'Written for the screen by Christopher Nolan',
  'Movie': 'Oppenheimer',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Adapted Screenplay)',
  'Name': 'Screenplay by Tony McNamara',
  'Movie': 'Poor Things',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Adapted Screenplay)',
  'Name': 'Written by Jonathan Glazer',
  'Movie': 'The Zone of Interest',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Original Screenplay)',
  'Name': 'Screenplay - Justine Triet and Arthur Harari',
  'Movie': 'Anatomy of a Fall',
  'Year': 2024,
  'Winner': 'Winner'},
 {'Category': 'Writing (Original Screenplay)',
  'Name': 'Written by David Hemingson',
  'Movie': 'The Holdovers',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Original Screenplay)',
  'Name': 'Written by Bradley Cooper & Josh Singer',
  'Movie': 'Maestro',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Original Screenplay)',
  'Name': 'Screenplay by Samy Burch; Story by Samy Burch & Alex Mechanik',
  'Movie': 'May December',
  'Year': 2024,
  'Winner': 'Nominees'},
 {'Category': 'Writing (Original Screenplay)',
  'Name': 'Written by Celine Song',
  'Movie': 'Past Lives',
  'Year': 2024,
  'Winner': 'Nominees'}]

## Iterating vs. parsing to retrieve data

Often the data you are interested in is spread across multiple web pages. In an ideal world, the naming conventions would let you retrieve the data from these pages systematically. In the case of the Oscars, the URLs appear to be consistently formatted: `https://www.oscars.org/oscars/ceremonies/2019` suggests that we could change the 2019 to any other date going back to the start of the Oscars and get that year as well: `https://www.oscars.org/oscars/ceremonies/2018` should get us the page for 2018, and so on. Let's demonstrate each of these strategies with the Oscars data: iterating from 2019 back to 1929 in the URL versus parsing the list of links from the header.

### Iterating strategies for retrieving data

The fundamental assumption with this strategy is that the data are stored at URLs in a consistent way that we can access sequentially. In the case of the Oscars, we *should* be able to simply pass each year to the URL in requests. Here we want to practice responsible data scraping by including a sleep between each request so that we do not overwhelm the Oscars server with requests. We can use the `sleep` function within `time`.

In [131]:
from time import sleep

The `sleep(3)` below prevents any more code from progressing for 3 seconds.

In [132]:
print("The start of something.")
sleep(5)
print("The end of something.")

The start of something.
The end of something.

The core part of the iterating strategy is simply using Python's [`range`](https://docs.python.org/3.7/library/functions.html#func-range) function to generate a sequence of values. Here, we can use `range` to print out a sequence of URLs that should correspond to awards pages from 2010 through 2019. We can also incorporate the `sleep` functionality and wait a second between each `print` statement—it should now take 10 seconds for this code to finish printing. This simulates how we can use `sleep` to slow down and spread out requests so that we do not overwhelm the servers whose data we are trying to scrape.

In [133]:
for year in range(2010,2025):
    sleep(1)
    print('https://www.oscars.org/oscars/ceremonies/{0}'.format(year))

https://www.oscars.org/oscars/ceremonies/2010
https://www.oscars.org/oscars/ceremonies/2011
https://www.oscars.org/oscars/ceremonies/2012
https://www.oscars.org/oscars/ceremonies/2013
https://www.oscars.org/oscars/ceremonies/2014
https://www.oscars.org/oscars/ceremonies/2015
https://www.oscars.org/oscars/ceremonies/2016
https://www.oscars.org/oscars/ceremonies/2017
https://www.oscars.org/oscars/ceremonies/2018
https://www.oscars.org/oscars/ceremonies/2019
https://www.oscars.org/oscars/ceremonies/2020
https://www.oscars.org/oscars/ceremonies/2021
https://www.oscars.org/oscars/ceremonies/2022
https://www.oscars.org/oscars/ceremonies/2023
https://www.oscars.org/oscars/ceremonies/2024

We defined a function `parse_nominees` above that takes the "true groups" of nominees. Let's try to tie these pieces together for all the nominees in the 2010s.

In [175]:
# Create an empty list to store the data we get
all_years_nominees = dict()

# For each year starting in 2010 until 2019
for year in range(1950,1960):
    
    # Pause for a second between each request
    sleep(1)
    
    # Get the raw HTML
    year_raw_html = requests.get('https://www.oscars.org/oscars/ceremonies/{0}'.format(year),headers=user_agent).text

    # Soup-ify
    oscars_soup = BeautifulSoup(year_raw_html)

    # Get the awards groups
    oscars_award_groups = oscars_soup.find_all('div',{'class':'paragraph--type--award-category'})
    
    # Use our parsing function, passing the year from above
    year_nominees = parse_nominees(oscars_award_groups,year)
    
    # Convert the year_nominees to a DataFrame and add them to all_years_nominees
    all_years_nominees[year] = pd.DataFrame(year_nominees)

Combine each of the DataFrames in `all_years_nominees` into a giant DataFrame of all the nominees from 2010-2019.

In [176]:
all_years_nominees_df = pd.concat(all_years_nominees)
all_years_nominees_df.reset_index(drop=True)

,Category,Name,Movie,Year,Winner
0,Actor,Broderick Crawford,All the King's Men,1950,Winner
1,Actor,Kirk Douglas,Champion,1950,Nominees
2,Actor,Gregory Peck,Twelve O'Clock High,1950,Nominees
3,Actor,Richard Todd,The Hasty Heart,1950,Nominees
4,Actor,John Wayne,Sands of Iwo Jima,1950,Nominees
...,...,...,...,...,...
1152,Writing (Story and Screenplay—written directly...,"Nedrick Young, Harold Jacob Smith",The Defiant Ones,1959,Winner
1153,Writing (Story and Screenplay—written directly...,Paddy Chayefsky,The Goddess,1959,Nominees
1154,Writing (Story and Screenplay—written directly...,"Melville Shavelson, Jack Rose",Houseboat,1959,Nominees
1155,Writing (Story and Screenplay—written directly...,Story by James Edward Grant; Screenplay by Wi...,The Sheepman,1959,Nominees
1156,Writing (Story and Screenplay—written directly...,"Fay Kanin, Michael Kanin",Teacher's Pet,1959,Nominees

In [ ]:
all_years_nominees_df['Name'].value_counts()

### Parsing strategy for retrieving data

Frustratingly, this iterating strategy may not always hold: maybe some years are skipped or the naming convention changes at some point. We will cover some basics of [error-handling in Python](https://realpython.com/python-exceptions/) that could let us work around errors as they pop up, but this may result in an incomplete collection if the naming conventions are systematic. What we would want to do is to identify all the links ahead of time by parsing them from list and then work through that list to get the complete data collection.

What this means in the context of our Oscars example is assuming that we cannot trust that the sequential numbering of the years is a realiable guide to get all the data. Instead, we should get a list of the URLs for each of the awards pages from the "ceremonies-decade-scroller" (from Inspect) at the top. This scroller *should* be consistent across all the pages, but start with the nominees for 2019 just to be safe:

In [ ]:
oscars2019_raw = requests.get('https://www.oscars.org/oscars/ceremonies/2019',headers=user_agent).text
oscars2019_soup = BeautifulSoup(oscars2019_raw)

Using the Inspect tool, there is a `<div class="years">` that contains the links to each of the years. Run a `.find_all` to get all these href locations.

In [ ]:
# Get the <div class="years"> as a parent tag first, just in case there are <a class="years"> elsewhere
oscars2019_years_div = oscars2019_soup.find_all('div',{'class':'years'})[0]

# Now get the <a class="years"> underneath only the oscars2019_years_div
oscars2019_years_a = oscars2019_years_div.find_all('a',{'class':'year'})

# Inspect the first 10
oscars2019_years_a[:10]

Each of these `<a>` tags contains an "href", or the URL element where the page lives, and a text element for what's displayed.

In [ ]:
oscars2019_years_a[0]['href']

In [ ]:
oscars2019_years_a[0].text

Now we can write a loop to print out the URL locations for all the other award years based on the "official" links in the "ceremonies-decade-scroller" navigation rather than assuming the years are sequential—I promise this will pay dividends in the future when inconsistent design wreaks havoc on your sequential data strategies!

In [ ]:
for a in oscars2019_years_a[-10:]:
    href = a['href']
    print('https://www.oscars.org' + href)

We can now use the `parse_nominees` function for these pages as well.

In [ ]:
# Create an empty list to store the data we get
all_years_nominees = dict()

# For the 10 most recent years
for a in oscars2019_years_a[-10:]:
    
    # Pause for a second between each request
    sleep(1)
    
    # Get the href
    href = a['href']
    
    # Get the year
    year = a.text
    
    # Get the raw HTML
    url = 'https://www.oscars.org' + href
    year_raw_html = requests.get(url,headers=user_agent).text

    # Soup-ify
    year_souped_html = BeautifulSoup(year_raw_html)
    
    # Get the parent group
    year_parent_group = year_souped_html.find_all('div',{'id':'quicktabs-tabpage-honorees-0'})
    
    # Get the true groups under the parent group
    year_true_groups = year_parent_group[0].find_all('div',{'class':'view-grouping'})
    
    # Use our parsing function, passing the year from above
    year_nominees = parse_nominees(year_true_groups,year)
    
    # Convert the year_nominees to a DataFrame and add them to all_years_nominees
    all_years_nominees[year] = pd.DataFrame(year_nominees)

Combine each of the DataFrames in `all_years_nominees` into a giant DataFrame of all the nominees from 2010-2019.

In [ ]:
all_years_nominees_df = pd.concat(all_years_nominees)
all_years_nominees_df.reset_index(drop=True).head(10)

In [ ]:
all_years_nominees_df['Winner'].value_counts()

## Exercises

Let's take a look at websites you're interested in scraping and see what kinds of challenges and opportunities exist for scraping their data.

### Exercise 01: Retrieve a table from a Wikipedia article

Retrieve the "Tallest buildings in the world" table from the "[List of tallest buildings](https://en.wikipedia.org/wiki/List_of_tallest_buildings)" Wikipedia article.

### Exercise 02: Retrieve the top-grossing movies of 2022
Retrieve the "[Top Grossing Movies of 2022](https://www.the-numbers.com/market/2022/summary)" table from The Numbers and parse into a DataFrame.

### Exercise 03: Retrieve corresponding Wikipedia pageviews
For each of the top 10 grossing movies of 2022, retrieve the corresponding Wikipedia article pageview counts ([docs](https://wikimedia.org/api/rest_v1/)) for January 1, 2022 through December 31, 2022.

In [ ]:
from urllib.parse import quote 

def get_pageviews(article_name,start='20220101',end='20221231'):
    article_title = quote(article_name)

    wiki_pvs_url = 'https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/{0}/daily/{1}/{2}'

    custom_headers = {'User-Agent':'cu-info-5871/0.0 (brian.keegan@colorado.edu)'}

    req = requests.get(
        url = wiki_pvs_url.format(article_title,start,end),
        headers = custom_headers
    )

    # TODO: Don't just return the JSON, you have to navigate into the JSON
    return req.json()

### Exercise 04: Compare box office performance with Wikipedia activity
Aggregate the Wikipedia pageview data into a total count of pageviews for the year. Combine the total pageview data with the total movie revenue data. Make a visualization to compare these two types of data.

### Exercise 05: Retrieve tweet data (hard!)
**This exercise may involve breaking X/Twitter's Terms of Service. Retrieving data about official accounts of public officials *should be* a fair use exception to this rule.**

Inspect the source code for the user timeline for the [@POTUS](https://twitter.com/potus) or [@WhiteHouse](https://twitter.com/WhiteHouse) X/Twitter accounts. Try to retrieve the content of the tweets on the account's timeline.

In [143]:
raw_html = requests.get('https://leg.colorado.gov/bills/hb24-1147',headers=user_agent).text

raw_html

'<!DOCTYPE html>\n<!--[if IEMobile 7]><html class="iem7"  lang="en" dir="ltr"><![endif]-->\n<!--[if lte IE 6]><html class="lt-ie9 lt-ie8 lt-ie7 no-js"  lang="en" dir="ltr"><![endif]-->\n<!--[if (IE 7)&(!IEMobile)]><html class="lt-ie9 lt-ie8 no-js"  lang="en" dir="ltr"><![endif]-->\n<!--[if IE 8]><html class="lt-ie9 no-js"  lang="en" dir="ltr"><![endif]-->\n<!--[if IE 9]><html class="ie9 lt-ie10 no-js"  lang="en" dir="ltr"><![endif]-->\n<!--[if (gt IE 9)|(gt IEMobile 7)]><!--><html class="no-js"  lang="en" dir="ltr" prefix="content: http://purl.org/rss/1.0/modules/content/ dc: http://purl.org/dc/terms/ foaf: http://xmlns.com/foaf/0.1/ og: http://ogp.me/ns# rdfs: http://www.w3.org/2000/01/rdf-schema# sioc: http://rdfs.org/sioc/ns# sioct: http://rdfs.org/sioc/types# skos: http://www.w3.org/2004/02/skos/core# xsd: http://www.w3.org/2001/XMLSchema#"><!--<![endif]-->\n\n<head>\n  <meta charset="utf-8" /><script type="text/javascript">(window.NREUM||(NREUM={})).init={ajax:{deny_list:["bam.nr-data.net"]}};(window.NREUM||(NREUM={})).loader_config={licenseKey:"48ca2afd60",applicationID:"65781041"};;/*! For license information please see nr-loader-rum-1.267.0.min.js.LICENSE.txt */\n(()=>{var e,t,r={8122:(e,t,r)=>{"use strict";r.d(t,{a:()=>i});var n=r(944);function i(e,t){try{if(!e||"object"!=typeof e)return(0,n.R)(3);if(!t||"object"!=typeof t)return(0,n.R)(4);const r=Object.create(Object.getPrototypeOf(t),Object.getOwnPropertyDescriptors(t)),o=0===Object.keys(r).length?e:r;for(let a in o)if(void 0!==e[a])try{if(null===e[a]){r[a]=null;continue}Array.isArray(e[a])&&Array.isArray(t[a])?r[a]=Array.from(new Set([...e[a],...t[a]])):"object"==typeof e[a]&&"object"==typeof t[a]?r[a]=i(e[a],t[a]):r[a]=e[a]}catch(e){(0,n.R)(1,e)}return r}catch(e){(0,n.R)(2,e)}}},2555:(e,t,r)=>{"use strict";r.d(t,{Vp:()=>c,fn:()=>s,x1:()=>u});var n=r(384),i=r(8122);const o={beacon:n.NT.beacon,errorBeacon:n.NT.errorBeacon,licenseKey:void 0,applicationID:void 0,sa:void 0,queueTime:void 0,applicationTime:void 0,ttGuid:void 0,user:void 0,account:void 0,product:void 0,extra:void 0,jsAttributes:{},userAttributes:void 0,atts:void 0,transactionName:void 0,tNamePlain:void 0},a={};function s(e){try{const t=c(e);return!!t.licenseKey&&!!t.errorBeacon&&!!t.applicationID}catch(e){return!1}}function c(e){if(!e)throw new Error("All info objects require an agent identifier!");if(!a[e])throw new Error("Info for ".concat(e," was never set"));return a[e]}function u(e,t){if(!e)throw new Error("All info objects require an agent identifier!");a[e]=(0,i.a)(t,o);const r=(0,n.nY)(e);r&&(r.info=a[e])}},9417:(e,t,r)=>{"use strict";r.d(t,{D0:()=>g,gD:()=>h,xN:()=>p});var n=r(993);const i=e=>{if(!e||"string"!=typeof e)return!1;try{document.createDocumentFragment().querySelector(e)}catch{return!1}return!0};var o=r(2614),a=r(944),s=r(384),c=r(8122);const u="[data-nr-mask]",d=()=>{const e={mask_selector:"*",block_selector:"[data-nr-block]",mask_input_options:{color:!1,date:!1,"datetime-local":!1,email:!1,month:!1,number:!1,range:!1,search:!1,tel:!1,text:!1,time:!1,url:!1,week:!1,textarea:!1,select:!1,password:!0}};return{ajax:{deny_list:void 0,block_internal:!0,enabled:!0,harvestTimeSeconds:10,autoStart:!0},distributed_tracing:{enabled:void 0,exclude_newrelic_header:void 0,cors_use_newrelic_header:void 0,cors_use_tracecontext_headers:void 0,allowed_origins:void 0},feature_flags:[],generic_events:{enabled:!0,harvestTimeSeconds:30,autoStart:!0},harvest:{tooManyRequestsDelay:60},jserrors:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},logging:{enabled:!0,harvestTimeSeconds:10,autoStart:!0,level:n.p_.INFO},metrics:{enabled:!0,autoStart:!0},obfuscate:void 0,page_action:{enabled:!0},page_view_event:{enabled:!0,autoStart:!0},page_view_timing:{enabled:!0,harvestTimeSeconds:30,autoStart:!0},privacy:{cookies_enabled:!0},proxy:{assets:void 0,beacon:void 0},session:{expiresMs:o.wk,inactiveMs:o.BB},session_replay:{autoStart:!0,enabled:!1,harvestTimeSeconds:60,preload:!1,sampling_rate:10,error_sampling_rate:100,collect_fonts:!1,inline_images:!1,fix_stylesheets:!0,mask_all_inputs:!0,get mask_text_selector(){return e.mask_selector},set mask_text_selector(t){i(t)?e.mask_selector="".concat(t,",").concat(u):""===t||null===t?e.mask_selector=u:(0,a.R)(5,t)},get block_class(){return"nr-block"},get ignore_class(){return"nr-ignore"},get mask_text_class(){return"nr-mask"},get block_selector(){return e.block_selector},set block_selector(t){i(t)?e.block_selector+=",".concat(t):""!==t&&(0,a.R)(6,t)},get mask_input_options(){return e.mask_input_options},set mask_input_options(t){t&&"object"==typeof t?e.mask_input_options={...t,password:!0}:(0,a.R)(7,t)}},session_trace:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},soft_navigations:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},spa:{enabled:!0,harvestTimeSeconds:10,autoStart:!0},ssl:void 0}},l={},f="All configuration objects require an agent identifier!";function g(e){if(!e)throw new Error(f);if(!l[e])throw new Error("Configuration for ".concat(e," was never set"));return l[e]}function p(e,t){if(!e)throw new Error(f);l[e]=(0,c.a)(t,d());const r=(0,s.nY)(e);r&&(r.init=l[e])}function h(e,t){if(!e)throw new Error(f);var r=g(e);if(r){for(var n=t.split("."),i=0;i<n.length-1;i++)if("object"!=typeof(r=r[n[i]]))return;r=r[n[n.length-1]]}return r}},3371:(e,t,r)=>{"use strict";r.d(t,{V:()=>f,f:()=>l});var n=r(8122),i=r(384),o=r(6154),a=r(9324);let s=0;const c={buildEnv:a.F3,distMethod:a.Xs,version:a.xv,originTime:o.WN},u={customTransaction:void 0,disabled:!1,isolatedBacklog:!1,loaderType:void 0,maxBytes:3e4,onerror:void 0,origin:""+o.gm.location,ptid:void 0,releaseIds:{},appMetadata:{},session:void 0,denyList:void 0,timeKeeper:void 0,obfuscator:void 0},d={};function l(e){if(!e)throw new Error("All runtime objects require an agent identifier!");if(!d[e])throw new Error("Runtime for ".concat(e," was never set"));return d[e]}function f(e,t){if(!e)throw new Error("All runtime objects require an agent identifier!");d[e]={...(0,n.a)(t,u),...c},Object.hasOwnProperty.call(d[e],"harvestCount")||Object.defineProperty(d[e],"harvestCount",{get:()=>++s});const r=(0,i.nY)(e);r&&(r.runtime=d[e])}},9324:(e,t,r)=>{"use strict";r.d(t,{F3:()=>i,Xs:()=>o,xv:()=>n});const n="1.267.0",i="PROD",o="CDN"},6154:(e,t,r)=>{"use strict";r.d(t,{OF:()=>c,RI:()=>i,Vr:()=>d,WN:()=>l,bv:()=>o,gm:()=>a,mw:()=>s,sb:()=>u});var n=r(1863);const i="undefined"!=typeof window&&!!window.document,o="undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self.navigator instanceof WorkerNavigator||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis.navigator instanceof WorkerNavigator),a=i?window:"undefined"!=typeof WorkerGlobalScope&&("undefined"!=typeof self&&self instanceof WorkerGlobalScope&&self||"undefined"!=typeof globalThis&&globalThis instanceof WorkerGlobalScope&&globalThis),s=Boolean("hidden"===a?.document?.visibilityState),c=/iPad|iPhone|iPod/.test(a.navigator?.userAgent),u=c&&"undefined"==typeof SharedWorker,d=((()=>{const e=a.navigator?.userAgent?.match(/Firefox[/\\s](\\d+\\.\\d+)/);Array.isArray(e)&&e.length>=2&&e[1]})(),!!a.navigator?.sendBeacon),l=Date.now()-(0,n.t)()},4777:(e,t,r)=>{"use strict";r.d(t,{J:()=>o});var n=r(944);const i={agentIdentifier:"",ee:void 0};class o{constructor(e){try{if("object"!=typeof e)return(0,n.R)(8);this.sharedContext={},Object.assign(this.sharedContext,i),Object.entries(e).forEach((([e,t])=>{Object.keys(i).includes(e)&&(this.sharedContext[e]=t)}))}catch(e){(0,n.R)(9,e)}}}},1687:(e,t,r)=>{"use strict";r.d(t,{Ak:()=>c,Ze:()=>l,x3:()=>u});var n=r(7836),i=r(3606),o=r(860),a=r(2646);const s={};function c(e,t){const r={staged:!1,priority:o.P[t]||0};d(e),s[e].get(t)||s[e].set(t,r)}function u(e,t){e&&s[e]&&(s[e].get(t)&&s[e].delete(t),g(e,t,!1),s[e].size&&f(e))}function d(e){if(!e)throw new Error("agentIdentifier required");s[e]||(s[e]=new Map)}function l(e="",t="feature",r=!1){if(d(e),!e||!s[e].get(t)||r)return g(e,t);s[e].get(t).staged=!0,f(e)}function f(e){const t=Array.from(s[e]);t.every((([e,t])=>t.staged))&&(t.sort(((e,t)=>e[1].priority-t[1].priority)),t.forEach((([t])=>{s[e].delete(t),g(e,t)})))}function g(e,t,r=!0){const o=e?n.ee.get(e):n.ee,s=i.i.handlers;if(!o.aborted&&o.backlog&&s){if(r){const e=o.backlog[t],r=s[t];if(r){for(let t=0;e&&t<e.length;++t)p(e[t],r);Object.entries(r).forEach((([e,t])=>{Object.values(t||{}).forEach((t=>{t[0]?.on&&t[0]?.context()instanceof a.y&&t[0].on(e,t[1])}))}))}}o.isolatedBacklog||delete s[t],o.backlog[t]=null,o.emit("drain-"+t,[])}}function p(e,t){var r=e[1];Object.values(t[r]||{}).forEach((t=>{var r=e[0];if(t[0]===r){var n=t[1],i=e[3],o=e[2];n.apply(i,o)}}))}},7836:(e,t,r)=>{"use strict";r.d(t,{P:()=>c,ee:()=>u});var n=r(384),i=r(8990),o=r(3371),a=r(2646),s=r(5607);const c="nr@context:".concat(s.W),u=function e(t,r){var n={},s={},d={},l=!1;try{l=16===r.length&&(0,o.f)(r).isolatedBacklog}catch(e){}var f={on:p,addEventListener:p,removeEventListener:function(e,t){var r=n[e];if(!r)return;for(var i=0;i<r.length;i++)r[i]===t&&r.splice(i,1)},emit:function(e,r,n,i,o){!1!==o&&(o=!0);if(u.aborted&&!i)return;t&&o&&t.emit(e,r,n);for(var a=g(n),c=h(e),d=c.length,l=0;l<d;l++)c[l].apply(a,r);var p=v()[s[e]];p&&p.push([f,e,r,a]);return a},get:m,listeners:h,context:g,buffer:function(e,t){const r=v();if(t=t||"feature",f.aborted)return;Object.entries(e||{}).forEach((([e,n])=>{s[n]=t,t in r||(r[t]=[])}))},abort:function(){f._aborted=!0,Object.keys(f.backlog).forEach((e=>{delete f.backlog[e]}))},isBuffering:function(e){return!!v()[s[e]]},debugId:r,backlog:l?{}:t&&"object"==typeof t.backlog?t.backlog:{},isolatedBacklog:l};return Object.defineProperty(f,"aborted",{get:()=>{let e=f._aborted||!1;return e||(t&&(e=t.aborted),e)}}),f;function g(e){return e&&e instanceof a.y?e:e?(0,i.I)(e,c,(()=>new a.y(c))):new a.y(c)}function p(e,t){n[e]=h(e).concat(t)}function h(e){return n[e]||[]}function m(t){return d[t]=d[t]||e(f,t)}function v(){return f.backlog}}(void 0,"globalEE"),d=(0,n.Zm)();d.ee||(d.ee=u)},2646:(e,t,r)=>{"use strict";r.d(t,{y:()=>n});class n{constructor(e){this.contextId=e}}},9908:(e,t,r)=>{"use strict";r.d(t,{d:()=>n,p:()=>i});var n=r(7836).ee.get("handle");function i(e,t,r,i,o){o?(o.buffer([e],i),o.emit(e,t,r)):(n.buffer([e],i),n.emit(e,t,r))}},3606:(e,t,r)=>{"use strict";r.d(t,{i:()=>o});var n=r(9908);o.on=a;var i=o.handlers={};function o(e,t,r,o){a(o||n.d,i,e,t,r)}function a(e,t,r,i,o){o||(o="feature"),e||(e=n.d);var a=t[o]=t[o]||{};(a[r]=a[r]||[]).push([e,i])}},3878:(e,t,r)=>{"use strict";r.d(t,{DD:()=>c,jT:()=>a,sp:()=>s});var n=r(6154);let i=!1,o=!1;try{const e={get passive(){return i=!0,!1},get signal(){return o=!0,!1}};n.gm.addEventListener("test",null,e),n.gm.removeEventListener("test",null,e)}catch(e){}function a(e,t){return i||o?{capture:!!e,passive:i,signal:t}:!!e}function s(e,t,r=!1,n){window.addEventListener(e,t,a(r,n))}function c(e,t,r=!1,n){document.addEventListener(e,t,a(r,n))}},5607:(e,t,r)=>{"use strict";r.d(t,{W:()=>n});const n=(0,r(9566).bz)()},9566:(e,t,r)=>{"use strict";r.d(t,{LA:()=>s,bz:()=>a});var n=r(6154);const i="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx";function o(e,t){return e?15&e[t]:16*Math.random()|0}function a(){const e=n.gm?.crypto||n.gm?.msCrypto;let t,r=0;return e&&e.getRandomValues&&(t=e.getRandomValues(new Uint8Array(30))),i.split("").map((e=>"x"===e?o(t,r++).toString(16):"y"===e?(3&o()|8).toString(16):e)).join("")}function s(e){const t=n.gm?.crypto||n.gm?.msCrypto;let r,i=0;t&&t.getRandomValues&&(r=t.getRandomValues(new Uint8Array(e)));const a=[];for(var s=0;s<e;s++)a.push(o(r,i++).toString(16));return a.join("")}},2614:(e,t,r)=>{"use strict";r.d(t,{BB:()=>a,H3:()=>n,g:()=>u,iL:()=>c,tS:()=>s,uh:()=>i,wk:()=>o});const n="NRBA",i="SESSION",o=144e5,a=18e5,s={STARTED:"session-started",PAUSE:"session-pause",RESET:"session-reset",RESUME:"session-resume",UPDATE:"session-update"},c={SAME_TAB:"same-tab",CROSS_TAB:"cross-tab"},u={OFF:0,FULL:1,ERROR:2}},1863:(e,t,r)=>{"use strict";function n(){return Math.floor(performance.now())}r.d(t,{t:()=>n})},944:(e,t,r)=>{"use strict";function n(e,t){"function"==typeof console.debug&&console.debug("New Relic Warning: https://github.com/newrelic/newrelic-browser-agent/blob/main/docs/warning-codes.md#".concat(e),t)}r.d(t,{R:()=>n})},5284:(e,t,r)=>{"use strict";r.d(t,{t:()=>c,B:()=>s});var n=r(7836),i=r(6154);const o="newrelic";const a=new Set,s={};function c(e,t){const r=n.ee.get(t);s[t]??={},e&&"object"==typeof e&&(a.has(t)||(r.emit("rumresp",[e]),s[t]=e,a.add(t),function(e={}){try{i.gm.dispatchEvent(new CustomEvent(o,{detail:e}))}catch(e){}}({loaded:!0})))}},8990:(e,t,r)=>{"use strict";r.d(t,{I:()=>i});var n=Object.prototype.hasOwnProperty;function i(e,t,r){if(n.call(e,t))return e[t];var i=r();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,t,{value:i,writable:!0,enumerable:!1}),i}catch(e){}return e[t]=i,i}},6389:(e,t,r)=>{"use strict";function n(e,t=500,r={}){const n=r?.leading||!1;let i;return(...r)=>{n&&void 0===i&&(e.apply(this,r),i=setTimeout((()=>{i=clearTimeout(i)}),t)),n||(clearTimeout(i),i=setTimeout((()=>{e.apply(this,r)}),t))}}function i(e){let t=!1;return(...r)=>{t||(t=!0,e.apply(this,r))}}r.d(t,{J:()=>i,s:()=>n})},5289:(e,t,r)=>{"use strict";r.d(t,{GG:()=>o,sB:()=>a});var n=r(3878);function i(){return"undefined"==typeof document||"complete"===document.readyState}function o(e,t){if(i())return e();(0,n.sp)("load",e,t)}function a(e){if(i())return e();(0,n.DD)("DOMContentLoaded",e)}},384:(e,t,r)=>{"use strict";r.d(t,{NT:()=>o,US:()=>d,Zm:()=>a,bQ:()=>c,dV:()=>s,nY:()=>u,pV:()=>l});var n=r(6154),i=r(1863);const o={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net"};function a(){return n.gm.NREUM||(n.gm.NREUM={}),void 0===n.gm.newrelic&&(n.gm.newrelic=n.gm.NREUM),n.gm.NREUM}function s(){let e=a();return e.o||(e.o={ST:n.gm.setTimeout,SI:n.gm.setImmediate,CT:n.gm.clearTimeout,XHR:n.gm.XMLHttpRequest,REQ:n.gm.Request,EV:n.gm.Event,PR:n.gm.Promise,MO:n.gm.MutationObserver,FETCH:n.gm.fetch,WS:n.gm.WebSocket}),e}function c(e,t){let r=a();r.initializedAgents??={},t.initializedAt={ms:(0,i.t)(),date:new Date},r.initializedAgents[e]=t}function u(e){let t=a();return t.initializedAgents?.[e]}function d(e,t){a()[e]=t}function l(){return function(){let e=a();const t=e.info||{};e.info={beacon:o.beacon,errorBeacon:o.errorBeacon,...t}}(),function(){let e=a();const t=e.init||{};e.init={...t}}(),s(),function(){let e=a();const t=e.loader_config||{};e.loader_config={...t}}(),a()}},2843:(e,t,r)=>{"use strict";r.d(t,{u:()=>i});var n=r(3878);function i(e,t=!1,r,i){(0,n.DD)("visibilitychange",(function(){if(t)return void("hidden"===document.visibilityState&&e());e(document.visibilityState)}),r,i)}},3434:(e,t,r)=>{"use strict";r.d(t,{YM:()=>c});var n=r(7836),i=r(5607);const o="nr@original:".concat(i.W);var a=Object.prototype.hasOwnProperty,s=!1;function c(e,t){return e||(e=n.ee),r.inPlace=function(e,t,n,i,o){n||(n="");const a="-"===n.charAt(0);for(let s=0;s<t.length;s++){const c=t[s],u=e[c];d(u)||(e[c]=r(u,a?c+n:n,i,c,o))}},r.flag=o,r;function r(t,r,n,s,c){return d(t)?t:(r||(r=""),nrWrapper[o]=t,function(e,t,r){if(Object.defineProperty&&Object.keys)try{return Object.keys(e).forEach((function(r){Object.defineProperty(t,r,{get:function(){return e[r]},set:function(t){return e[r]=t,t}})})),t}catch(e){u([e],r)}for(var n in e)a.call(e,n)&&(t[n]=e[n])}(t,nrWrapper,e),nrWrapper);function nrWrapper(){var o,a,d,l;try{a=this,o=[...arguments],d="function"==typeof n?n(o,a):n||{}}catch(t){u([t,"",[o,a,s],d],e)}i(r+"start",[o,a,s],d,c);try{return l=t.apply(a,o)}catch(e){throw i(r+"err",[o,a,e],d,c),e}finally{i(r+"end",[o,a,l],d,c)}}}function i(r,n,i,o){if(!s||t){var a=s;s=!0;try{e.emit(r,n,i,t,o)}catch(t){u([t,r,n,i],e)}s=a}}}function u(e,t){t||(t=n.ee);try{t.emit("internal-error",e)}catch(e){}}function d(e){return!(e&&"function"==typeof e&&e.apply&&!e[o])}},993:(e,t,r)=>{"use strict";r.d(t,{ET:()=>o,p_:()=>i});var n=r(860);const i={ERROR:"ERROR",WARN:"WARN",INFO:"INFO",DEBUG:"DEBUG",TRACE:"TRACE"},o="log";n.K.logging},3969:(e,t,r)=>{"use strict";r.d(t,{TZ:()=>n,XG:()=>s,rs:()=>i,xV:()=>a,z_:()=>o});const n=r(860).K.metrics,i="sm",o="cm",a="storeSupportabilityMetrics",s="storeEventMetrics"},6630:(e,t,r)=>{"use strict";r.d(t,{T:()=>n});const n=r(860).K.pageViewEvent},782:(e,t,r)=>{"use strict";r.d(t,{T:()=>n});const n=r(860).K.pageViewTiming},6344:(e,t,r)=>{"use strict";r.d(t,{G4:()=>i});var n=r(2614);r(860).K.sessionReplay;const i={RECORD:"recordReplay",PAUSE:"pauseReplay",REPLAY_RUNNING:"replayRunning",ERROR_DURING_REPLAY:"errorDuringReplay"};n.g.ERROR,n.g.FULL,n.g.OFF},4234:(e,t,r)=>{"use strict";r.d(t,{W:()=>i});var n=r(7836);class i{constructor(e,t,r){this.agentIdentifier=e,this.aggregator=t,this.ee=n.ee.get(e),this.featureName=r,this.blocked=!1}}},7603:(e,t,r)=>{"use strict";r.d(t,{j:()=>P});var n=r(860),i=r(2555),o=r(3371),a=r(9908),s=r(7836),c=r(1687),u=r(5289),d=r(6154),l=r(944),f=r(3969),g=r(384),p=r(6344);const h=["setErrorHandler","finished","addToTrace","addRelease","addPageAction","setCurrentRouteName","setPageViewName","setCustomAttribute","interaction","noticeError","setUserId","setApplicationVersion","start",p.G4.RECORD,p.G4.PAUSE,"log","wrapLogger"],m=["setErrorHandler","finished","addToTrace","addRelease"];var v=r(1863),b=r(2614),y=r(993);var w=r(2646),R=r(3434);function A(e,t,r,n){if("object"!=typeof t||!t||"string"!=typeof r||!r||"function"!=typeof t[r])return(0,l.R)(29);const i=function(e){return(e||s.ee).get("logger")}(e),o=(0,R.YM)(i),a=new w.y(s.P);return a.level=n.level,a.customAttributes=n.customAttributes,o.inPlace(t,[r],"wrap-logger-",a),i}function x(){const e=(0,g.pV)();h.forEach((t=>{e[t]=(...r)=>function(t,...r){let n=[];return Object.values(e.initializedAgents).forEach((e=>{e&&e.api?e.exposed&&e.api[t]&&n.push(e.api[t](...r)):(0,l.R)(38,t)})),n.length>1?n:n[0]}(t,...r)}))}const E={};function _(e,t,g=!1){t||(0,c.Ak)(e,"api");const h={};var w=s.ee.get(e),R=w.get("tracer");E[e]=b.g.OFF,w.on(p.G4.REPLAY_RUNNING,(t=>{E[e]=t}));var x="api-",_=x+"ixn-";function N(t,r,n,o){const a=(0,i.Vp)(e);return null===r?delete a.jsAttributes[t]:(0,i.x1)(e,{...a,jsAttributes:{...a.jsAttributes,[t]:r}}),S(x,n,!0,o||null===r?"session":void 0)(t,r)}function T(){}h.log=function(e,{customAttributes:t={},level:r=y.p_.INFO}={}){(0,a.p)(f.xV,["API/log/called"],void 0,n.K.metrics,w),function(e,t,r={},i=y.p_.INFO){(0,a.p)(f.xV,["API/logging/".concat(i.toLowerCase(),"/called")],void 0,n.K.metrics,e),(0,a.p)(y.ET,[(0,v.t)(),t,r,i],void 0,n.K.logging,e)}(w,e,t,r)},h.wrapLogger=(e,t,{customAttributes:r={},level:i=y.p_.INFO}={})=>{(0,a.p)(f.xV,["API/wrapLogger/called"],void 0,n.K.metrics,w),A(w,e,t,{customAttributes:r,level:i})},m.forEach((e=>{h[e]=S(x,e,!0,"api")})),h.addPageAction=S(x,"addPageAction",!0,n.K.genericEvents),h.setPageViewName=function(t,r){if("string"==typeof t)return"/"!==t.charAt(0)&&(t="/"+t),(0,o.f)(e).customTransaction=(r||"http://custom.transaction")+t,S(x,"setPageViewName",!0)()},h.setCustomAttribute=function(e,t,r=!1){if("string"==typeof e){if(["string","number","boolean"].includes(typeof t)||null===t)return N(e,t,"setCustomAttribute",r);(0,l.R)(40,typeof t)}else(0,l.R)(39,typeof e)},h.setUserId=function(e){if("string"==typeof e||null===e)return N("enduser.id",e,"setUserId",!0);(0,l.R)(41,typeof e)},h.setApplicationVersion=function(e){if("string"==typeof e||null===e)return N("application.version",e,"setApplicationVersion",!1);(0,l.R)(42,typeof e)},h.start=()=>{try{(0,a.p)(f.xV,["API/start/called"],void 0,n.K.metrics,w),w.emit("manual-start-all")}catch(e){(0,l.R)(23,e)}},h[p.G4.RECORD]=function(){(0,a.p)(f.xV,["API/recordReplay/called"],void 0,n.K.metrics,w),(0,a.p)(p.G4.RECORD,[],void 0,n.K.sessionReplay,w)},h[p.G4.PAUSE]=function(){(0,a.p)(f.xV,["API/pauseReplay/called"],void 0,n.K.metrics,w),(0,a.p)(p.G4.PAUSE,[],void 0,n.K.sessionReplay,w)},h.interaction=function(e){return(new T).get("object"==typeof e?e:{})};const k=T.prototype={createTracer:function(e,t){var r={},i=this,o="function"==type

In [144]:
leg_soup = BeautifulSoup(raw_html)

In [149]:
leg_soup.find('div',{'id':"block-cga-bills-bill-sponsors"}).find_all('div',{'class':'member'})

[<div class="member">
 <div class="member-image">
 <a href="/legislators/junie-joseph"><img alt="Representative" src="https://leg.colorado.gov/sites/default/files/styles/profile_picture_teaser/public/2024b_joseph%2Cjunie.jpg?itok=cLoUsKep"/></a> </div>
 <div class="member-details">
 <span class="member-title">Representative</span>
 <h4><a href="/legislators/junie-joseph">Junie Joseph</a></h4>
 </div>
 </div>,
 <div class="member">
 <div class="member-image">
 <a href="/legislators/brianna-titone"><img alt="Representative" src="https://leg.colorado.gov/sites/default/files/styles/profile_picture_teaser/public/2024b_titone%2Cbrianna.jpg?itok=YzCwDK_Z"/></a> </div>
 <div class="member-details">
 <span class="member-title">Representative</span>
 <h4><a href="/legislators/brianna-titone">Brianna Titone</a></h4>
 </div>
 </div>,
 <div class="member">
 <div class="member-image">
 <a href="/legislators/chris-hansen"><img alt="Senator" src="https://leg.colorado.gov/sites/default/files/styles/profile_picture_teaser/public/2024b_hansen%2Cchris.jpg?itok=hSISrQsS"/></a> </div>
 <div class="member-details">
 <span class="member-title">Senator</span>
 <h4><a href="/legislators/chris-hansen">Chris Hansen</a></h4>
 </div>
 </div>,
 <div class="member">
 <div class="member-image">
 <a href="/legislators/janet-buckner"><img alt="Senator" src="https://leg.colorado.gov/sites/default/files/styles/profile_picture_teaser/public/2024b_buckner%2Cjanet-.jpg?itok=pY2PkAsZ"/></a> </div>
 <div class="member-details">
 <span class="member-title">Senator</span>
 <h4><a href="/legislators/janet-buckner">Janet Buckner</a></h4>
 </div>
 </div>]

In [150]:
leg_soup.find('div',{'id':"block-cga-bills-bill-committees"})

<div class="block block-cga-bills last odd" id="block-cga-bills-bill-committees">
<div class="block-container">
<div class="block-title-container">
<h2 class="block__title block-title">Committees</h2>
</div>
<div class="block-content">
<div class="committee-item">
<div class="small-label">
      House    </div>
<h4><a href="/committees/state-civic-military-veterans-affairs/2024-regular-session">State, Civic, Military, &amp; Veterans Affairs</a></h4>
<div class="small-label">
      Senate    </div>
<h4><a href="/committees/state-veterans-military-affairs/2024-regular-session">State, Veterans, &amp; Military Affairs</a></h4>
</div> </div>
</div>
</div>

## Final project down payment

1. Find a legislator from the list of current Colorado legislators: https://leg.colorado.gov/legislators/
2. `requests.get` their biograpaphy page
3. Parse out some of their basic demographic information: party, occupation, district, committees
4. Store this information in a dictionary

In [162]:
# Get the page
joseph_raw = requests.get('https://leg.colorado.gov/legislators/brianna-titone').text

# Turn into soup
joseph_soup = BeautifulSoup(joseph_raw)

# Find party affiliation
joseph_soup.find('div',{'class':'field-name-field-political-affiliation'}).find('div',{'class':'even'}).text

'Democrat'

In [164]:
joseph_soup.find('div',{'class':'field-name-field-leadership-position'}).find('div',{'class':'even'}).text

'Majority Caucus Co-Chair'

In [166]:
joseph_soup.find('h1').text

'Brianna Titone'

In [170]:
joseph_soup.find_all('div',{'class':'committee-assignment'})[0].h4.text

'Joint Technology Committee'

In [171]:
joseph_soup.find_all('div',{'class':'committee-assignment'})[1].h4.text

'Agriculture, Water & Natural Resources'

In [172]:
joseph_soup.find_all('div',{'class':'committee-assignment'})[2].h4.text

'Energy & Environment'

In [173]:
joseph_soup.find_all('div',{'class':'committee-assignment'})[3].h4.text

IndexError: list index out of range